package ni.org.ics.zpo.appmovil.helpers;

import android.content.ContentValues;
import android.database.Cursor;
import ni.org.ics.zpo.domain.Zpo01StudyEntrySectionAtoB;
import ni.org.ics.zpo.domain.Zpo01StudyEntrySectionC;
import ni.org.ics.zpo.domain.Zpo01StudyEntrySectionDtoF;
import ni.org.ics.zpo.appmovil.utils.MainDBConstants;
import ni.org.ics.zpo.appmovil.utils.Zpo01DBConstants;

import java.util.Date;

/**
 * Helper para el parseo del formulario Zp01StudyEntry
 * Todas las secciones: A-B, C y D-F
 * Created by FIRSTICT on 10/20/2016.
 * V1.0
 */
public class Zpo01StudyEntryHelper {

    /**********************************************************/
    /********** PARA OBJETO Zpo01StudyEntrySectionAtoB *********/
    /**********************************************************/
    public static ContentValues crearZpo01StudyEntrySectionAtoBValues(Zpo01StudyEntrySectionAtoB studyEntrySectionAtoD){
        ContentValues cv = new ContentValues();

        cv.put(Zpo01DBConstants.recordId, studyEntrySectionAtoD.getRecordId());
        cv.put(Zpo01DBConstants.eventName, studyEntrySectionAtoD.getEventName());
        if (studyEntrySectionAtoD.getSeaVdate() != null) cv.put(Zpo01DBConstants.seaVdate, studyEntrySectionAtoD.getSeaVdate().getTime());
        if (studyEntrySectionAtoD.getSeaBirthdate() != null) cv.put(Zpo01DBConstants.seaBirthdate, studyEntrySectionAtoD.getSeaBirthdate().getTime());
        cv.put(Zpo01DBConstants.seaPregnantBefore, studyEntrySectionAtoD.getSeaPregnantBefore());
        cv.put(Zpo01DBConstants.seaPregStillDeliAfter, studyEntrySectionAtoD.getSeaPregStillDeliAfter());
        cv.put(Zpo01DBConstants.seaCity, studyEntrySectionAtoD.getSeaCity());
        cv.put(Zpo01DBConstants.seaState, studyEntrySectionAtoD.getSeaState());
        cv.put(Zpo01DBConstants.seaCountry, studyEntrySectionAtoD.getSeaCountry());
        cv.put(Zpo01DBConstants.seaLive, studyEntrySectionAtoD.getSeaLive());
        cv.put(Zpo01DBConstants.seaAgeLeave, studyEntrySectionAtoD.getSeaAgeLeave());
        cv.put(Zpo01DBConstants.seaLeavena, studyEntrySectionAtoD.getSeaLeavena());
        cv.put(Zpo01DBConstants.seaMstatus, studyEntrySectionAtoD.getSeaMstatus());
        cv.put(Zpo01DBConstants.seaRace, studyEntrySectionAtoD.getSeaRace());
        cv.put(Zpo01DBConstants.seaEthnicityOther, studyEntrySectionAtoD.getSeaEthnicityOther());
        cv.put(Zpo01DBConstants.seaDegreeYou, studyEntrySectionAtoD.getSeaDegreeYou());
        cv.put(Zpo01DBConstants.seaYdegreeYears, studyEntrySectionAtoD.getSeaYdegreeYears());
        cv.put(Zpo01DBConstants.seaDegreeSpouse, studyEntrySectionAtoD.getSeaDegreeSpouse());
        cv.put(Zpo01DBConstants.seaSdegreeYears, studyEntrySectionAtoD.getSeaSdegreeYears());

        if (studyEntrySectionAtoD.getRecordDate() != null) cv.put(MainDBConstants.recordDate, studyEntrySectionAtoD.getRecordDate().getTime());
        cv.put(MainDBConstants.recordUser, studyEntrySectionAtoD.getRecordUser());
        cv.put(MainDBConstants.pasive, String.valueOf(studyEntrySectionAtoD.getPasive()));
        cv.put(MainDBConstants.ID_INSTANCIA, studyEntrySectionAtoD.getIdInstancia());
        cv.put(MainDBConstants.FILE_PATH, studyEntrySectionAtoD.getInstancePath());
        cv.put(MainDBConstants.STATUS, studyEntrySectionAtoD.getEstado());
        cv.put(MainDBConstants.START, studyEntrySectionAtoD.getStart());
        cv.put(MainDBConstants.END, studyEntrySectionAtoD.getEnd());
        cv.put(MainDBConstants.DEVICE_ID, studyEntrySectionAtoD.getDeviceid());
        cv.put(MainDBConstants.SIM_SERIAL, studyEntrySectionAtoD.getSimserial());
        cv.put(MainDBConstants.PHONE_NUMBER, studyEntrySectionAtoD.getPhonenumber());
        if (studyEntrySectionAtoD.getToday() != null) cv.put(MainDBConstants.TODAY, studyEntrySectionAtoD.getToday().getTime());

        return cv;
    }

    public static Zpo01StudyEntrySectionAtoB crearZpo01StudyEntrySectionAtoB(Cursor cursorAtoD){
        Zpo01StudyEntrySectionAtoB studyEntrySectionAtoD = new Zpo01StudyEntrySectionAtoB();
        studyEntrySectionAtoD.setRecordId(cursorAtoD.getString(cursorAtoD.getColumnIndex(Zpo01DBConstants.recordId)));
        studyEntrySectionAtoD.setEventName(cursorAtoD.getString(cursorAtoD.getColumnIndex(Zpo01DBConstants.eventName)));
        if (cursorAtoD.getLong(cursorAtoD.getColumnIndex(Zpo01DBConstants.seaVdate))>0) studyEntrySectionAtoD.setSeaVdate(new Date(cursorAtoD.getLong(cursorAtoD.getColumnIndex(Zpo01DBConstants.seaVdate))));
        if (cursorAtoD.getLong(cursorAtoD.getColumnIndex(Zpo01DBConstants.seaBirthdate))>0) studyEntrySectionAtoD.setSeaBirthdate(new Date(cursorAtoD.getLong(cursorAtoD.getColumnIndex(Zpo01DBConstants.seaBirthdate))));
        studyEntrySectionAtoD.setSeaPregnantBefore(cursorAtoD.getString(cursorAtoD.getColumnIndex(Zpo01DBConstants.seaPregnantBefore)));
        studyEntrySectionAtoD.setSeaPregStillDeliAfter(cursorAtoD.getString(cursorAtoD.getColumnIndex(Zpo01DBConstants.seaPregStillDeliAfter)));
        studyEntrySectionAtoD.setSeaCity(cursorAtoD.getString(cursorAtoD.getColumnIndex(Zpo01DBConstants.seaCity)));
        studyEntrySectionAtoD.setSeaState(cursorAtoD.getString(cursorAtoD.getColumnIndex(Zpo01DBConstants.seaState)));
        studyEntrySectionAtoD.setSeaCountry(cursorAtoD.getString(cursorAtoD.getColumnIndex(Zpo01DBConstants.seaCountry)));
        studyEntrySectionAtoD.setSeaLive(cursorAtoD.getString(cursorAtoD.getColumnIndex(Zpo01DBConstants.seaLive)));
        if(cursorAtoD.getString(cursorAtoD.getColumnIndex(Zpo01DBConstants.seaLive)) != null && cursorAtoD.getString(cursorAtoD.getColumnIndex(Zpo01DBConstants.seaLive)).equals("0")) studyEntrySectionAtoD.setSeaAgeLeave(cursorAtoD.getInt(cursorAtoD.getColumnIndex(Zpo01DBConstants.seaAgeLeave)));
        studyEntrySectionAtoD.setSeaLeavena(cursorAtoD.getString(cursorAtoD.getColumnIndex(Zpo01DBConstants.seaLeavena)));
        studyEntrySectionAtoD.setSeaMstatus(cursorAtoD.getString(cursorAtoD.getColumnIndex(Zpo01DBConstants.seaMstatus)));
        studyEntrySectionAtoD.setSeaRace(cursorAtoD.getString(cursorAtoD.getColumnIndex(Zpo01DBConstants.seaRace)));
        studyEntrySectionAtoD.setSeaEthnicityOther(cursorAtoD.getString(cursorAtoD.getColumnIndex(Zpo01DBConstants.seaEthnicityOther)));
        studyEntrySectionAtoD.setSeaDegreeYou(cursorAtoD.getString(cursorAtoD.getColumnIndex(Zpo01DBConstants.seaDegreeYou)));
        studyEntrySectionAtoD.setSeaYdegreeYears(cursorAtoD.getFloat(cursorAtoD.getColumnIndex(Zpo01DBConstants.seaYdegreeYears)));
        studyEntrySectionAtoD.setSeaDegreeSpouse(cursorAtoD.getString(cursorAtoD.getColumnIndex(Zpo01DBConstants.seaDegreeSpouse)));
        studyEntrySectionAtoD.setSeaSdegreeYears(cursorAtoD.getFloat(cursorAtoD.getColumnIndex(Zpo01DBConstants.seaSdegreeYears)));

        //Movil y Metadata
        if(cursorAtoD.getLong(cursorAtoD.getColumnIndex(MainDBConstants.recordDate))>0) studyEntrySectionAtoD.setRecordDate(new Date(cursorAtoD.getLong(cursorAtoD.getColumnIndex(MainDBConstants.recordDate))));
        studyEntrySectionAtoD.setRecordUser(cursorAtoD.getString(cursorAtoD.getColumnIndex(MainDBConstants.recordUser)));
        studyEntrySectionAtoD.setPasive(cursorAtoD.getString(cursorAtoD.getColumnIndex(MainDBConstants.pasive)).charAt(0));
        studyEntrySectionAtoD.setIdInstancia(cursorAtoD.getInt(cursorAtoD.getColumnIndex(MainDBConstants.ID_INSTANCIA)));
        studyEntrySectionAtoD.setInstancePath(cursorAtoD.getString(cursorAtoD.getColumnIndex(MainDBConstants.FILE_PATH)));
        studyEntrySectionAtoD.setEstado(cursorAtoD.getString(cursorAtoD.getColumnIndex(MainDBConstants.STATUS)));
        studyEntrySectionAtoD.setStart(cursorAtoD.getString(cursorAtoD.getColumnIndex(MainDBConstants.START)));
        studyEntrySectionAtoD.setEnd(cursorAtoD.getString(cursorAtoD.getColumnIndex(MainDBConstants.END)));
        studyEntrySectionAtoD.setSimserial(cursorAtoD.getString(cursorAtoD.getColumnIndex(MainDBConstants.SIM_SERIAL)));
        studyEntrySectionAtoD.setPhonenumber(cursorAtoD.getString(cursorAtoD.getColumnIndex(MainDBConstants.PHONE_NUMBER)));
        studyEntrySectionAtoD.setDeviceid(cursorAtoD.getString(cursorAtoD.getColumnIndex(MainDBConstants.DEVICE_ID)));
        if(cursorAtoD.getLong(cursorAtoD.getColumnIndex(MainDBConstants.TODAY))>0) studyEntrySectionAtoD.setToday(new Date(cursorAtoD.getLong(cursorAtoD.getColumnIndex(MainDBConstants.TODAY))));

        return studyEntrySectionAtoD;
    }

    /**********************************************************/
    /********** PARA OBJETO Zpo01StudyEntrySectionC *********/
    /**********************************************************/
    public static ContentValues crearZpo01StudyEntrySectionCValues(Zpo01StudyEntrySectionC studyEntrySectionE){
        ContentValues cv = new ContentValues();
        cv.put(Zpo01DBConstants.recordId, studyEntrySectionE.getRecordId());
        cv.put(Zpo01DBConstants.eventName, studyEntrySectionE.getEventName());
        cv.put(Zpo01DBConstants.seaDiseases, studyEntrySectionE.getSeaDiseases());
        cv.put(Zpo01DBConstants.seaOtherSpecify, studyEntrySectionE.getSeaOtherSpecify());
        cv.put(Zpo01DBConstants.seaHepatitis, studyEntrySectionE.getSeaHepatitis());
        if (studyEntrySectionE.getSeaHepatitisDate1()!=null) cv.put(Zpo01DBConstants.seaHepatitisDate1, studyEntrySectionE.getSeaHepatitisDate1().getTime());
        if (studyEntrySectionE.getSeaHepatitisDate2()!=null) cv.put(Zpo01DBConstants.seaHepatitisDate2, studyEntrySectionE.getSeaHepatitisDate2().getTime());
        if (studyEntrySectionE.getSeaHepatitisDate3()!=null) cv.put(Zpo01DBConstants.seaHepatitisDate3, studyEntrySectionE.getSeaHepatitisDate3().getTime());
        cv.put(Zpo01DBConstants.seaMeasles, studyEntrySectionE.getSeaMeasles());
        if (studyEntrySectionE.getSeaMeaslesDate1()!=null) cv.put(Zpo01DBConstants.seaMeaslesDate1, studyEntrySectionE.getSeaMeaslesDate1().getTime());
        if (studyEntrySectionE.getSeaMeaslesDate2()!=null) cv.put(Zpo01DBConstants.seaMeaslesDate2, studyEntrySectionE.getSeaMeaslesDate2().getTime());
        if (studyEntrySectionE.getSeaMeaslesDate3()!=null) cv.put(Zpo01DBConstants.seaMeaslesDate3, studyEntrySectionE.getSeaMeaslesDate3().getTime());
        cv.put(Zpo01DBConstants.seaChickenpox, studyEntrySectionE.getSeaChickenpox());
        if (studyEntrySectionE.getSeaChickenpoxDate1()!=null) cv.put(Zpo01DBConstants.seaChickenpoxDate1, studyEntrySectionE.getSeaChickenpoxDate1().getTime());
        if (studyEntrySectionE.getSeaChickenpoxDate2()!=null) cv.put(Zpo01DBConstants.seaChickenpoxDate2, studyEntrySectionE.getSeaChickenpoxDate2().getTime());
        if (studyEntrySectionE.getSeaChickenpoxDate3()!=null) cv.put(Zpo01DBConstants.seaChickenpoxDate3, studyEntrySectionE.getSeaChickenpoxDate3().getTime());
        cv.put(Zpo01DBConstants.seaInfluenza, studyEntrySectionE.getSeaInfluenza());
        if (studyEntrySectionE.getSeaInfluenzaDate1()!=null) cv.put(Zpo01DBConstants.seaInfluenzaDate1, studyEntrySectionE.getSeaInfluenzaDate1().getTime());
        if (studyEntrySectionE.getSeaInfluenzaDate2()!=null) cv.put(Zpo01DBConstants.seaInfluenzaDate2, studyEntrySectionE.getSeaInfluenzaDate2().getTime());
        if (studyEntrySectionE.getSeaInfluenzaDate3()!=null) cv.put(Zpo01DBConstants.seaInfluenzaDate3, studyEntrySectionE.getSeaInfluenzaDate3().getTime());
        cv.put(Zpo01DBConstants.seaYellow, studyEntrySectionE.getSeaYellow());
        if (studyEntrySectionE.getSeaYellowDate1()!=null) cv.put(Zpo01DBConstants.seaYellowDate1, studyEntrySectionE.getSeaYellowDate1().getTime());
        if (studyEntrySectionE.getSeaYellowDate2()!=null) cv.put(Zpo01DBConstants.seaYellowDate2, studyEntrySectionE.getSeaYellowDate2().getTime());
        if (studyEntrySectionE.getSeaYellowDate3()!=null) cv.put(Zpo01DBConstants.seaYellowDate3, studyEntrySectionE.getSeaYellowDate3().getTime());
        cv.put(Zpo01DBConstants.seaDengue, studyEntrySectionE.getSeaDengue());
        if (studyEntrySectionE.getSeaDengueDate1()!=null) cv.put(Zpo01DBConstants.seaDengueDate1, studyEntrySectionE.getSeaDengueDate1().getTime());
        if (studyEntrySectionE.getSeaDengueDate2()!=null) cv.put(Zpo01DBConstants.seaDengueDate2, studyEntrySectionE.getSeaDengueDate2().getTime());
        if (studyEntrySectionE.getSeaDengueDate3()!=null) cv.put(Zpo01DBConstants.seaDengueDate3, studyEntrySectionE.getSeaDengueDate3().getTime());
        cv.put(Zpo01DBConstants.seaVacOther, studyEntrySectionE.getSeaVacOther());
        cv.put(Zpo01DBConstants.seaVacotherSpecify, studyEntrySectionE.getSeaVacotherSpecify());
        if (studyEntrySectionE.getSeaOtherDate1()!=null) cv.put(Zpo01DBConstants.seaOtherDate1, studyEntrySectionE.getSeaOtherDate1().getTime());
        if (studyEntrySectionE.getSeaOtherDate2()!=null) cv.put(Zpo01DBConstants.seaOtherDate2, studyEntrySectionE.getSeaOtherDate2().getTime());
        if (studyEntrySectionE.getSeaOtherDate3()!=null) cv.put(Zpo01DBConstants.seaOtherDate3, studyEntrySectionE.getSeaOtherDate3().getTime());
        cv.put(Zpo01DBConstants.seaRubella, studyEntrySectionE.getSeaRubella());
        if (studyEntrySectionE.getSeaRubellaDate1()!=null) cv.put(Zpo01DBConstants.seaRubellaDate1, studyEntrySectionE.getSeaRubellaDate1().getTime());
        if (studyEntrySectionE.getSeaRubellaDate2()!=null) cv.put(Zpo01DBConstants.seaRubellaDate2, studyEntrySectionE.getSeaRubellaDate2().getTime());
        if (studyEntrySectionE.getSeaRubellaDate3()!=null) cv.put(Zpo01DBConstants.seaRubellaDate3, studyEntrySectionE.getSeaRubellaDate3().getTime());
        cv.put(Zpo01DBConstants.seaRubellaDoc, studyEntrySectionE.getSeaRubellaDoc());
        cv.put(Zpo01DBConstants.seaCmv, studyEntrySectionE.getSeaCmv());
        if (studyEntrySectionE.getSeaCmvDate1()!=null) cv.put(Zpo01DBConstants.seaCmvDate1, studyEntrySectionE.getSeaCmvDate1().getTime());
        if (studyEntrySectionE.getSeaCmvDate2()!=null) cv.put(Zpo01DBConstants.seaCmvDate2, studyEntrySectionE.getSeaCmvDate2().getTime());
        if (studyEntrySectionE.getSeaCmvDate3()!=null) cv.put(Zpo01DBConstants.seaCmvDate3, studyEntrySectionE.getSeaCmvDate3().getTime());
        cv.put(Zpo01DBConstants.seaCmvDoc, studyEntrySectionE.getSeaCmvDoc());
        cv.put(Zpo01DBConstants.seaHerpes, studyEntrySectionE.getSeaHerpes());
        if (studyEntrySectionE.getSeaHerpesDate1()!=null )cv.put(Zpo01DBConstants.seaHerpesDate1, studyEntrySectionE.getSeaHerpesDate1().getTime());
        if (studyEntrySectionE.getSeaHerpesDate2()!=null) cv.put(Zpo01DBConstants.seaHerpesDate2, studyEntrySectionE.getSeaHerpesDate2().getTime());
        if (studyEntrySectionE.getSeaHerpesDate3()!=null) cv.put(Zpo01DBConstants.seaHerpesDate3, studyEntrySectionE.getSeaHerpesDate3().getTime());
        cv.put(Zpo01DBConstants.seaHerpesDoc, studyEntrySectionE.getSeaHerpesDoc());
        cv.put(Zpo01DBConstants.seaParvovirus, studyEntrySectionE.getSeaParvovirus());
        if (studyEntrySectionE.getSeaParvovirusDate1()!=null) cv.put(Zpo01DBConstants.seaParvovirusDate1, studyEntrySectionE.getSeaParvovirusDate1().getTime());
        if (studyEntrySectionE.getSeaParvovirusDate2()!=null) cv.put(Zpo01DBConstants.seaParvovirusDate2, studyEntrySectionE.getSeaParvovirusDate2().getTime());
        if (studyEntrySectionE.getSeaParvovirusDate3()!=null) cv.put(Zpo01DBConstants.seaParvovirusDate3, studyEntrySectionE.getSeaParvovirusDate3().getTime());
        cv.put(Zpo01DBConstants.seaParvovirusDoc, studyEntrySectionE.getSeaParvovirusDoc());
        cv.put(Zpo01DBConstants.seaToxoplasmosis, studyEntrySectionE.getSeaToxoplasmosis());
        if (studyEntrySectionE.getSeaToxoplasmosisDate1()!=null) cv.put(Zpo01DBConstants.seaToxoplasmosisDate1, studyEntrySectionE.getSeaToxoplasmosisDate1().getTime());
        if (studyEntrySectionE.getSeaToxoplasmosisDate2()!=null) cv.put(Zpo01DBConstants.seaToxoplasmosisDate2, studyEntrySectionE.getSeaToxoplasmosisDate2().getTime());
        if (studyEntrySectionE.getSeaToxoplasmosisDate3()!=null) cv.put(Zpo01DBConstants.seaToxoplasmosisDate3, studyEntrySectionE.getSeaToxoplasmosisDate3().getTime());
        cv.put(Zpo01DBConstants.seaToxoplasmosisDoc, studyEntrySectionE.getSeaToxoplasmosisDoc());
        cv.put(Zpo01DBConstants.seaSyphillis, studyEntrySectionE.getSeaSyphillis());
        if (studyEntrySectionE.getSeaSyphillisDate1()!=null) cv.put(Zpo01DBConstants.seaSyphillisDate1, studyEntrySectionE.getSeaSyphillisDate1().getTime());
        if (studyEntrySectionE.getSeaSyphillisDate2()!=null) cv.put(Zpo01DBConstants.seaSyphillisDate2, studyEntrySectionE.getSeaSyphillisDate2().getTime());
        if (studyEntrySectionE.getSeaSyphillisDate3()!=null) cv.put(Zpo01DBConstants.seaSyphillisDate3, studyEntrySectionE.getSeaSyphillisDate3().getTime());
        cv.put(Zpo01DBConstants.seaSyphillisDoc, studyEntrySectionE.getSeaSyphillisDoc());
        cv.put(Zpo01DBConstants.seaHiv, studyEntrySectionE.getSeaHiv());
        if (studyEntrySectionE.getSeaHivDate1()!=null) cv.put(Zpo01DBConstants.seaHivDate1, studyEntrySectionE.getSeaHivDate1().getTime());
        if (studyEntrySectionE.getSeaHivDate2()!=null) cv.put(Zpo01DBConstants.seaHivDate2, studyEntrySectionE.getSeaHivDate2().getTime());
        if (studyEntrySectionE.getSeaHivDate3()!=null) cv.put(Zpo01DBConstants.seaHivDate3, studyEntrySectionE.getSeaHivDate3().getTime());
        cv.put(Zpo01DBConstants.seaHivDoc, studyEntrySectionE.getSeaHivDoc());
        cv.put(Zpo01DBConstants.seaZika, studyEntrySectionE.getSeaZika());
        if (studyEntrySectionE.getSeaZikaDate1()!=null) cv.put(Zpo01DBConstants.seaZikaDate1, studyEntrySectionE.getSeaZikaDate1().getTime());
        if (studyEntrySectionE.getSeaZikaDate2()!=null) cv.put(Zpo01DBConstants.seaZikaDate2, studyEntrySectionE.getSeaZikaDate2().getTime());
        if (studyEntrySectionE.getSeaZikaDate3()!=null) cv.put(Zpo01DBConstants.seaZikaDate3, studyEntrySectionE.getSeaZikaDate3().getTime());
        cv.put(Zpo01DBConstants.seaZikaDoc, studyEntrySectionE.getSeaZikaDoc());
        cv.put(Zpo01DBConstants.seaChikung, studyEntrySectionE.getSeaChikung());
        if (studyEntrySectionE.getSeaChikungDate1()!=null) cv.put(Zpo01DBConstants.seaChikungDate1, studyEntrySectionE.getSeaChikungDate1().getTime());
        if (studyEntrySectionE.getSeaChikungDate2()!=null) cv.put(Zpo01DBConstants.seaChikungDate2, studyEntrySectionE.getSeaChikungDate2().getTime());
        if (studyEntrySectionE.getSeaChikungDate3()!=null) cv.put(Zpo01DBConstants.seaChikungDate3, studyEntrySectionE.getSeaChikungDate3().getTime());
        cv.put(Zpo01DBConstants.seaChikungDoc, studyEntrySectionE.getSeaChikungDoc());
        cv.put(Zpo01DBConstants.seaInfluInfect, studyEntrySectionE.getSeaInfluInfect());
        if (studyEntrySectionE.getSeaInflueInfectDate1()!=null) cv.put(Zpo01DBConstants.seaInflueInfectDate1, studyEntrySectionE.getSeaInflueInfectDate1().getTime());
        if (studyEntrySectionE.getSeaInfluInfectDate2()!=null) cv.put(Zpo01DBConstants.seaInfluInfectDate2, studyEntrySectionE.getSeaInfluInfectDate2().getTime());
        if (studyEntrySectionE.getSeaInfluInfectDate3()!=null) cv.put(Zpo01DBConstants.seaInfluInfectDate3, studyEntrySectionE.getSeaInfluInfectDate3().getTime());
        cv.put(Zpo01DBConstants.seaInfluInfectDoc, studyEntrySectionE.getSeaInfluInfectDoc());
        cv.put(Zpo01DBConstants.seaDengueInfect, studyEntrySectionE.getSeaDengueInfect());
        if (studyEntrySectionE.getSeaDengueInfectDate1()!=null)cv.put(Zpo01DBConstants.seaDengueInfectDate1, studyEntrySectionE.getSeaDengueInfectDate1().getTime());
        if (studyEntrySectionE.getSeaDengueInfectDate2()!=null) cv.put(Zpo01DBConstants.seaDengueInfectDate2, studyEntrySectionE.getSeaDengueInfectDate2().getTime());
        if (studyEntrySectionE.getSeaDengueInfectDate3()!=null) cv.put(Zpo01DBConstants.seaDengueInfectDate3, studyEntrySectionE.getSeaDengueInfectDate3().getTime());
        cv.put(Zpo01DBConstants.seaDengueInfectDoc, studyEntrySectionE.getSeaDengueInfectDoc());
        cv.put(Zpo01DBConstants.seaFeverSymptom, studyEntrySectionE.getSeaFeverSymptom());
        cv.put(Zpo01DBConstants.seaRash, studyEntrySectionE.getSeaRash());
        cv.put(Zpo01DBConstants.seaItch, studyEntrySectionE.getSeaItch());
        cv.put(Zpo01DBConstants.seaRashFirst, studyEntrySectionE.getSeaRashFirst());
        cv.put(Zpo01DBConstants.seaRashDay, studyEntrySectionE.getSeaRashDay());
        cv.put(Zpo01DBConstants.seaRashMonth, studyEntrySectionE.getSeaRashMonth());
        cv.put(Zpo01DBConstants.seaRashYear, studyEntrySectionE.getSeaRashYear());
        cv.put(Zpo01DBConstants.seaRashDuration, studyEntrySectionE.getSeaRashDuration());
        cv.put(Zpo01DBConstants.seaRashSpread, studyEntrySectionE.getSeaRashSpread());
        cv.put(Zpo01DBConstants.seaSpreadPart, studyEntrySectionE.getSeaSpreadPart());
        cv.put(Zpo01DBConstants.seaFeverExperience, studyEntrySectionE.getSeaFeverExperience());
        cv.put(Zpo01DBConstants.seaTempMeasure, studyEntrySectionE.getSeaTempMeasure());
        cv.put(Zpo01DBConstants.seaHighTemp, studyEntrySectionE.getSeaHighTemp());
        cv.put(Zpo01DBConstants.seaHightemUnit, studyEntrySectionE.getSeaHightemUnit());
        cv.put(Zpo01DBConstants.seaTempunknown, studyEntrySectionE.getSeaTempunknown());
        cv.put(Zpo01DBConstants.seaFeverDay, studyEntrySectionE.getSeaFeverDay());
        cv.put(Zpo01DBConstants.seaFeverMonth, studyEntrySectionE.getSeaFeverMonth());
        cv.put(Zpo01DBConstants.seaFeverYear, studyEntrySectionE.getSeaFeverYear());
        cv.put(Zpo01DBConstants.seaFeverDuration, studyEntrySectionE.getSeaFeverDuration());
        cv.put(Zpo01DBConstants.seaFDurationunknown, studyEntrySectionE.getSeaFDurationunknown());
        cv.put(Zpo01DBConstants.seaRedeyes, studyEntrySectionE.getSeaRedeyes());
        cv.put(Zpo01DBConstants.seaRedeyesDay, studyEntrySectionE.getSeaRedeyesDay());
        cv.put(Zpo01DBConstants.seaRedeyesMonth, studyEntrySectionE.getSeaRedeyesMonth());
        cv.put(Zpo01DBConstants.seaRedeyesYear, studyEntrySectionE.getSeaRedeyesYear());
        cv.put(Zpo01DBConstants.seaRedeyesDuration, studyEntrySectionE.getSeaRedeyesDuration());
        cv.put(Zpo01DBConstants.seaOccurSame, studyEntrySectionE.getSeaOccurSame());
        cv.put(Zpo01DBConstants.seaSameSymptom, studyEntrySectionE.getSeaSameSymptom());
        cv.put(Zpo01DBConstants.seaJoint, studyEntrySectionE.getSeaJoint());
        cv.put(Zpo01DBConstants.seaJointDay, studyEntrySectionE.getSeaJointDay());
        cv.put(Zpo01DBConstants.seaJointMonth, studyEntrySectionE.getSeaJointMonth());
        cv.put(Zpo01DBConstants.seaJointYear, studyEntrySectionE.getSeaJointYear());
        cv.put(Zpo01DBConstants.seaJointDuration, studyEntrySectionE.getSeaJointDuration());
        cv.put(Zpo01DBConstants.seaHeadache, studyEntrySectionE.getSeaHeadache());
        cv.put(Zpo01DBConstants.seaHeadacheDay, studyEntrySectionE.getSeaHeadacheDay());
        cv.put(Zpo01DBConstants.seaHeadacheMonth, studyEntrySectionE.getSeaHeadacheMonth());
        cv.put(Zpo01DBConstants.seaHeadacheYear, studyEntrySectionE.getSeaHeadacheYear());
        cv.put(Zpo01DBConstants.seaHeadacheDuration, studyEntrySectionE.getSeaHeadacheDuration());
        cv.put(Zpo01DBConstants.seaSymptomOther, studyEntrySectionE.getSeaSymptomOther());
        cv.put(Zpo01DBConstants.seaSpecifySymptom, studyEntrySectionE.getSeaSpecifySymptom());
        cv.put(Zpo01DBConstants.seaOtherSymptom, studyEntrySectionE.getSeaOtherSymptom());
        cv.put(Zpo01DBConstants.seaMedicare, studyEntrySectionE.getSeaMedicare());
        cv.put(Zpo01DBConstants.seaCareDay, studyEntrySectionE.getSeaCareDay());
        cv.put(Zpo01DBConstants.seaCareMonth, studyEntrySectionE.getSeaCareMonth());
        cv.put(Zpo01DBConstants.seaCareYear, studyEntrySectionE.getSeaCareYear());
        cv.put(Zpo01DBConstants.seaCareFacility, studyEntrySectionE.getSeaCareFacility());
        cv.put(Zpo01DBConstants.seaHospitalized, studyEntrySectionE.getSeaHospitalized());
        cv.put(Zpo01DBConstants.seaHospital, studyEntrySectionE.getSeaHospital());
        cv.put(Zpo01DBConstants.seaDiagRubella, studyEntrySectionE.getSeaDiagRubella());
        cv.put(Zpo01DBConstants.seaDiagDengue, studyEntrySectionE.getSeaDiagDengue());
        cv.put(Zpo01DBConstants.seaDiagChikung, studyEntrySectionE.getSeaDiagChikung());
        cv.put(Zpo01DBConstants.seaDiagZika, studyEntrySectionE.getSeaDiagZika());
        cv.put(Zpo01DBConstants.seaDiagCytome, studyEntrySectionE.getSeaDiagCytome());
        cv.put(Zpo01DBConstants.seaMedicine, studyEntrySectionE.getSeaMedicine());
        cv.put(Zpo01DBConstants.seaMedcineName, studyEntrySectionE.getSeaMedcineName());
        cv.put(Zpo01DBConstants.seaGuillainbarre, studyEntrySectionE.getSeaGuillainbarre());
        cv.put(Zpo01DBConstants.seaTingling, studyEntrySectionE.getSeaTingling());
        cv.put(Zpo01DBConstants.seaTinglingArm, studyEntrySectionE.getSeaTinglingArm());
        cv.put(Zpo01DBConstants.seaTinglingLeg, studyEntrySectionE.getSeaTinglingLeg());
        cv.put(Zpo01DBConstants.seaTinglingHand, studyEntrySectionE.getSeaTinglingHand());
        cv.put(Zpo01DBConstants.seaTinglingFoot, studyEntrySectionE.getSeaTinglingFoot());
        cv.put(Zpo01DBConstants.seaTinglingFace, studyEntrySectionE.getSeaTinglingFace());
        cv.put(Zpo01DBConstants.seaTinglingOther, studyEntrySectionE.getSeaTinglingOther());
        cv.put(Zpo01DBConstants.seaSensationMin, studyEntrySectionE.getSeaSensationMin());
        cv.put(Zpo01DBConstants.seaSensationHr, studyEntrySectionE.getSeaSensationHr());
        cv.put(Zpo01DBConstants.seaSenstaionDay, studyEntrySectionE.getSeaSenstaionDay());
        cv.put(Zpo01DBConstants.seaInjury, studyEntrySectionE.getSeaInjury());
        cv.put(Zpo01DBConstants.seaTinglingDay, studyEntrySectionE.getSeaTinglingDay());
        cv.put(Zpo01DBConstants.seaTinglingMonth, studyEntrySectionE.getSeaTinglingMonth());
        cv.put(Zpo01DBConstants.seaTinglingYear, studyEntrySectionE.getSeaTinglingYear());
        cv.put(Zpo01DBConstants.seaTinglingDuration, studyEntrySectionE.getSeaTinglingDuration());
        cv.put(Zpo01DBConstants.seaNumbness, studyEntrySectionE.getSeaNumbness());
        cv.put(Zpo01DBConstants.seaNumbArm, studyEntrySectionE.getSeaNumbArm());
        cv.put(Zpo01DBConstants.seaNumbLeg, studyEntrySectionE.getSeaNumbLeg());
        cv.put(Zpo01DBConstants.seaNumbHand, studyEntrySectionE.getSeaNumbHand());
        cv.put(Zpo01DBConstants.seaNumbFoot, studyEntrySectionE.getSeaNumbFoot());
        cv.put(Zpo01DBConstants.seaNumbFace, studyEntrySectionE.getSeaNumbFace());
        cv.put(Zpo01DBConstants.seaNumbOther, studyEntrySectionE.getSeaNumbOther());
        cv.put(Zpo01DBConstants.seaNumbDay, studyEntrySectionE.getSeaNumbDay());
        cv.put(Zpo01DBConstants.seaNumbMonth, studyEntrySectionE.getSeaNumbMonth());
        cv.put(Zpo01DBConstants.seaNumbYear, studyEntrySectionE.getSeaNumbYear());
        cv.put(Zpo01DBConstants.seaNumbDuration, studyEntrySectionE.getSeaNumbDuration());
        cv.put(Zpo01DBConstants.seaParalysis, studyEntrySectionE.getSeaParalysis());
        cv.put(Zpo01DBConstants.seaParaArm, studyEntrySectionE.getSeaParaArm());
        cv.put(Zpo01DBConstants.seaParaLeg, studyEntrySectionE.getSeaParaLeg());
        cv.put(Zpo01DBConstants.seaParaHand, studyEntrySectionE.getSeaParaHand());
        cv.put(Zpo01DBConstants.seaParaFoot, studyEntrySectionE.getSeaParaFoot());
        cv.put(Zpo01DBConstants.seaParaFace, studyEntrySectionE.getSeaParaFace());
        cv.put(Zpo01DBConstants.seaParaOther, studyEntrySectionE.getSeaParaOther());
        cv.put(Zpo01DBConstants.seaParaDay, studyEntrySectionE.getSeaParaDay());
        cv.put(Zpo01DBConstants.seaParaMonth, studyEntrySectionE.getSeaParaMonth());
        cv.put(Zpo01DBConstants.seaParaYear, studyEntrySectionE.getSeaParaYear());
        cv.put(Zpo01DBConstants.seaParaDuration, studyEntrySectionE.getSeaParaDuration());

        if (studyEntrySectionE.getRecordDate() != null) cv.put(MainDBConstants.recordDate, studyEntrySectionE.getRecordDate().getTime());
        cv.put(MainDBConstants.recordUser, studyEntrySectionE.getRecordUser());
        cv.put(MainDBConstants.pasive, String.valueOf(studyEntrySectionE.getPasive()));
        cv.put(MainDBConstants.ID_INSTANCIA, studyEntrySectionE.getIdInstancia());
        cv.put(MainDBConstants.FILE_PATH, studyEntrySectionE.getInstancePath());
        cv.put(MainDBConstants.STATUS, studyEntrySectionE.getEstado());
        cv.put(MainDBConstants.START, studyEntrySectionE.getStart());
        cv.put(MainDBConstants.END, studyEntrySectionE.getEnd());
        cv.put(MainDBConstants.DEVICE_ID, studyEntrySectionE.getDeviceid());
        cv.put(MainDBConstants.SIM_SERIAL, studyEntrySectionE.getSimserial());
        cv.put(MainDBConstants.PHONE_NUMBER, studyEntrySectionE.getPhonenumber());
        if (studyEntrySectionE.getToday() != null) cv.put(MainDBConstants.TODAY, studyEntrySectionE.getToday().getTime());

        return cv;
    }

    public static Zpo01StudyEntrySectionC crearZpo01StudyEntrySectionC(Cursor cursorE){
        Zpo01StudyEntrySectionC studyEntrySectionE = new Zpo01StudyEntrySectionC();
        studyEntrySectionE.setRecordId(cursorE.getString(cursorE.getColumnIndex(Zpo01DBConstants.recordId)));
        studyEntrySectionE.setEventName(cursorE.getString(cursorE.getColumnIndex(Zpo01DBConstants.eventName)));
        studyEntrySectionE.setSeaDiseases(cursorE.getString(cursorE.getColumnIndex(Zpo01DBConstants.seaDiseases)));
        studyEntrySectionE.setSeaOtherSpecify(cursorE.getString(cursorE.getColumnIndex(Zpo01DBConstants.seaOtherSpecify)));
        studyEntrySectionE.setSeaHepatitis(cursorE.getString(cursorE.getColumnIndex(Zpo01DBConstants.seaHepatitis)));
        if (cursorE.getLong(cursorE.getColumnIndex(Zpo01DBConstants.seaHepatitisDate1))>0) studyEntrySectionE.setSeaHepatitisDate1(new Date(cursorE.getLong(cursorE.getColumnIndex(Zpo01DBConstants.seaHepatitisDate1))));
        if (cursorE.getLong(cursorE.getColumnIndex(Zpo01DBConstants.seaHepatitisDate2))>0) studyEntrySectionE.setSeaHepatitisDate2(new Date(cursorE.getLong(cursorE.getColumnIndex(Zpo01DBConstants.seaHepatitisDate2))));
        if (cursorE.getLong(cursorE.getColumnIndex(Zpo01DBConstants.seaHepatitisDate3))>0) studyEntrySectionE.setSeaHepatitisDate3(new Date(cursorE.getLong(cursorE.getColumnIndex(Zpo01DBConstants.seaHepatitisDate3))));
        studyEntrySectionE.setSeaMeasles(cursorE.getString(cursorE.getColumnIndex(Zpo01DBConstants.seaMeasles)));
        if (cursorE.getLong(cursorE.getColumnIndex(Zpo01DBConstants.seaMeaslesDate1))>0) studyEntrySectionE.setSeaMeaslesDate1(new Date(cursorE.getLong(cursorE.getColumnIndex(Zpo01DBConstants.seaMeaslesDate1))));
        if (cursorE.getLong(cursorE.getColumnIndex(Zpo01DBConstants.seaMeaslesDate2))>0) studyEntrySectionE.setSeaMeaslesDate2(new Date(cursorE.getLong(cursorE.getColumnIndex(Zpo01DBConstants.seaMeaslesDate2))));
        if (cursorE.getLong(cursorE.getColumnIndex(Zpo01DBConstants.seaMeaslesDate3))>0) studyEntrySectionE.setSeaMeaslesDate3(new Date(cursorE.getLong(cursorE.getColumnIndex(Zpo01DBConstants.seaMeaslesDate3))));
        studyEntrySectionE.setSeaChickenpox(cursorE.getString(cursorE.getColumnIndex(Zpo01DBConstants.seaChickenpox)));
        if (cursorE.getLong(cursorE.getColumnIndex(Zpo01DBConstants.seaChickenpoxDate1))>0) studyEntrySectionE.setSeaChickenpoxDate1(new Date(cursorE.getLong(cursorE.getColumnIndex(Zpo01DBConstants.seaChickenpoxDate1))));
        if (cursorE.getLong(cursorE.getColumnIndex(Zpo01DBConstants.seaChickenpoxDate2))>0) studyEntrySectionE.setSeaChickenpoxDate2(new Date(cursorE.getLong(cursorE.getColumnIndex(Zpo01DBConstants.seaChickenpoxDate2))));
        if (cursorE.getLong(cursorE.getColumnIndex(Zpo01DBConstants.seaChickenpoxDate3))>0) studyEntrySectionE.setSeaChickenpoxDate3(new Date(cursorE.getLong(cursorE.getColumnIndex(Zpo01DBConstants.seaChickenpoxDate3))));
        studyEntrySectionE.setSeaInfluenza(cursorE.getString(cursorE.getColumnIndex(Zpo01DBConstants.seaInfluenza)));
        if (cursorE.getLong(cursorE.getColumnIndex(Zpo01DBConstants.seaInfluenzaDate1))>0) studyEntrySectionE.setSeaInfluenzaDate1(new Date(cursorE.getLong(cursorE.getColumnIndex(Zpo01DBConstants.seaInfluenzaDate1))));
        if (cursorE.getLong(cursorE.getColumnIndex(Zpo01DBConstants.seaInfluenzaDate2))>0) studyEntrySectionE.setSeaInfluenzaDate2(new Date(cursorE.getLong(cursorE.getColumnIndex(Zpo01DBConstants.seaInfluenzaDate2))));
        if (cursorE.getLong(cursorE.getColumnIndex(Zpo01DBConstants.seaInfluenzaDate3))>0) studyEntrySectionE.setSeaInfluenzaDate3(new Date(cursorE.getLong(cursorE.getColumnIndex(Zpo01DBConstants.seaInfluenzaDate3))));
        studyEntrySectionE.setSeaYellow(cursorE.getString(cursorE.getColumnIndex(Zpo01DBConstants.seaYellow)));
        if (cursorE.getLong(cursorE.getColumnIndex(Zpo01DBConstants.seaYellowDate1))>0) studyEntrySectionE.setSeaYellowDate1(new Date(cursorE.getLong(cursorE.getColumnIndex(Zpo01DBConstants.seaYellowDate1))));
        if (cursorE.getLong(cursorE.getColumnIndex(Zpo01DBConstants.seaYellowDate2))>0) studyEntrySectionE.setSeaYellowDate2(new Date(cursorE.getLong(cursorE.getColumnIndex(Zpo01DBConstants.seaYellowDate2))));
        if (cursorE.getLong(cursorE.getColumnIndex(Zpo01DBConstants.seaYellowDate3))>0) studyEntrySectionE.setSeaYellowDate3(new Date(cursorE.getLong(cursorE.getColumnIndex(Zpo01DBConstants.seaYellowDate3))));
        studyEntrySectionE.setSeaDengue(cursorE.getString(cursorE.getColumnIndex(Zpo01DBConstants.seaDengue)));
        if (cursorE.getLong(cursorE.getColumnIndex(Zpo01DBConstants.seaDengueDate1))>0) studyEntrySectionE.setSeaDengueDate1(new Date(cursorE.getLong(cursorE.getColumnIndex(Zpo01DBConstants.seaDengueDate1))));
        if (cursorE.getLong(cursorE.getColumnIndex(Zpo01DBConstants.seaDengueDate2))>0) studyEntrySectionE.setSeaDengueDate2(new Date(cursorE.getLong(cursorE.getColumnIndex(Zpo01DBConstants.seaDengueDate2))));
        if (cursorE.getLong(cursorE.getColumnIndex(Zpo01DBConstants.seaDengueDate3))>0) studyEntrySectionE.setSeaDengueDate3(new Date(cursorE.getLong(cursorE.getColumnIndex(Zpo01DBConstants.seaDengueDate3))));
        studyEntrySectionE.setSeaVacOther(cursorE.getString(cursorE.getColumnIndex(Zpo01DBConstants.seaVacOther)));
        studyEntrySectionE.setSeaVacotherSpecify(cursorE.getString(cursorE.getColumnIndex(Zpo01DBConstants.seaVacotherSpecify)));
        if (cursorE.getLong(cursorE.getColumnIndex(Zpo01DBConstants.seaOtherDate1))>0) studyEntrySectionE.setSeaOtherDate1(new Date(cursorE.getLong(cursorE.getColumnIndex(Zpo01DBConstants.seaOtherDate1))));
        if (cursorE.getLong(cursorE.getColumnIndex(Zpo01DBConstants.seaOtherDate2))>0) studyEntrySectionE.setSeaOtherDate1(new Date(cursorE.getLong(cursorE.getColumnIndex(Zpo01DBConstants.seaOtherDate2))));
        if (cursorE.getLong(cursorE.getColumnIndex(Zpo01DBConstants.seaOtherDate3))>0) studyEntrySectionE.setSeaOtherDate2(new Date(cursorE.getLong(cursorE.getColumnIndex(Zpo01DBConstants.seaOtherDate3))));
        studyEntrySectionE.setSeaRubella(cursorE.getString(cursorE.getColumnIndex(Zpo01DBConstants.seaRubella)));
        if (cursorE.getLong(cursorE.getColumnIndex(Zpo01DBConstants.seaRubellaDate1))>0) studyEntrySectionE.setSeaRubellaDate1(new Date(cursorE.getLong(cursorE.getColumnIndex(Zpo01DBConstants.seaRubellaDate1))));
        if (cursorE.getLong(cursorE.getColumnIndex(Zpo01DBConstants.seaRubellaDate2))>0) studyEntrySectionE.setSeaRubellaDate2(new Date(cursorE.getLong(cursorE.getColumnIndex(Zpo01DBConstants.seaRubellaDate2))));
        if (cursorE.getLong(cursorE.getColumnIndex(Zpo01DBConstants.seaRubellaDate3))>0) studyEntrySectionE.setSeaRubellaDate3(new Date(cursorE.getLong(cursorE.getColumnIndex(Zpo01DBConstants.seaRubellaDate3))));
        studyEntrySectionE.setSeaRubellaDoc(cursorE.getString(cursorE.getColumnIndex(Zpo01DBConstants.seaRubellaDoc)));
        studyEntrySectionE.setSeaCmv(cursorE.getString(cursorE.getColumnIndex(Zpo01DBConstants.seaCmv)));
        if (cursorE.getLong(cursorE.getColumnIndex(Zpo01DBConstants.seaCmvDate1))>0) studyEntrySectionE.setSeaCmvDate1(new Date(cursorE.getLong(cursorE.getColumnIndex(Zpo01DBConstants.seaCmvDate1))));
        if (cursorE.getLong(cursorE.getColumnIndex(Zpo01DBConstants.seaCmvDate2))>0) studyEntrySectionE.setSeaCmvDate2(new Date(cursorE.getLong(cursorE.getColumnIndex(Zpo01DBConstants.seaCmvDate2))));
        if (cursorE.getLong(cursorE.getColumnIndex(Zpo01DBConstants.seaCmvDate3))>0) studyEntrySectionE.setSeaCmvDate3(new Date(cursorE.getLong(cursorE.getColumnIndex(Zpo01DBConstants.seaCmvDate3))));
        studyEntrySectionE.setSeaCmvDoc(cursorE.getString(cursorE.getColumnIndex(Zpo01DBConstants.seaCmvDoc)));
        studyEntrySectionE.setSeaHerpes(cursorE.getString(cursorE.getColumnIndex(Zpo01DBConstants.seaHerpes)));
        if (cursorE.getLong(cursorE.getColumnIndex(Zpo01DBConstants.seaHerpesDate1))>0) studyEntrySectionE.setSeaHerpesDate1(new Date(cursorE.getLong(cursorE.getColumnIndex(Zpo01DBConstants.seaHerpesDate1))));
        if (cursorE.getLong(cursorE.getColumnIndex(Zpo01DBConstants.seaHerpesDate2))>0) studyEntrySectionE.setSeaHerpesDate2(new Date(cursorE.getLong(cursorE.getColumnIndex(Zpo01DBConstants.seaHerpesDate2))));
        if (cursorE.getLong(cursorE.getColumnIndex(Zpo01DBConstants.seaHerpesDate3))>0) studyEntrySectionE.setSeaHerpesDate3(new Date(cursorE.getLong(cursorE.getColumnIndex(Zpo01DBConstants.seaHerpesDate3))));
        studyEntrySectionE.setSeaHerpesDoc(cursorE.getString(cursorE.getColumnIndex(Zpo01DBConstants.seaHerpesDoc)));
        studyEntrySectionE.setSeaParvovirus(cursorE.getString(cursorE.getColumnIndex(Zpo01DBConstants.seaParvovirus)));
        if (cursorE.getLong(cursorE.getColumnIndex(Zpo01DBConstants.seaParvovirusDate1))>0) studyEntrySectionE.setSeaParvovirusDate1(new Date(cursorE.getLong(cursorE.getColumnIndex(Zpo01DBConstants.seaParvovirusDate1))));
        if (cursorE.getLong(cursorE.getColumnIndex(Zpo01DBConstants.seaParvovirusDate2))>0) studyEntrySectionE.setSeaParvovirusDate2(new Date(cursorE.getLong(cursorE.getColumnIndex(Zpo01DBConstants.seaParvovirusDate2))));
        if (cursorE.getLong(cursorE.getColumnIndex(Zpo01DBConstants.seaParvovirusDate3))>0) studyEntrySectionE.setSeaParvovirusDate3(new Date(cursorE.getLong(cursorE.getColumnIndex(Zpo01DBConstants.seaParvovirusDate3))));
        studyEntrySectionE.setSeaParvovirusDoc(cursorE.getString(cursorE.getColumnIndex(Zpo01DBConstants.seaParvovirusDoc)));
        studyEntrySectionE.setSeaToxoplasmosis(cursorE.getString(cursorE.getColumnIndex(Zpo01DBConstants.seaToxoplasmosis)));
        if (cursorE.getLong(cursorE.getColumnIndex(Zpo01DBConstants.seaToxoplasmosisDate1))>0) studyEntrySectionE.setSeaToxoplasmosisDate1(new Date(cursorE.getLong(cursorE.getColumnIndex(Zpo01DBConstants.seaToxoplasmosisDate1))));
        if (cursorE.getLong(cursorE.getColumnIndex(Zpo01DBConstants.seaToxoplasmosisDate2))>0) studyEntrySectionE.setSeaToxoplasmosisDate2(new Date(cursorE.getLong(cursorE.getColumnIndex(Zpo01DBConstants.seaToxoplasmosisDate2))));
        if (cursorE.getLong(cursorE.getColumnIndex(Zpo01DBConstants.seaToxoplasmosisDate3))>0) studyEntrySectionE.setSeaToxoplasmosisDate3(new Date(cursorE.getLong(cursorE.getColumnIndex(Zpo01DBConstants.seaToxoplasmosisDate3))));
        studyEntrySectionE.setSeaToxoplasmosisDoc(cursorE.getString(cursorE.getColumnIndex(Zpo01DBConstants.seaToxoplasmosisDoc)));
        studyEntrySectionE.setSeaSyphillis(cursorE.getString(cursorE.getColumnIndex(Zpo01DBConstants.seaSyphillis)));
        if (cursorE.getLong(cursorE.getColumnIndex(Zpo01DBConstants.seaSyphillisDate1))>0) studyEntrySectionE.setSeaSyphillisDate1(new Date(cursorE.getLong(cursorE.getColumnIndex(Zpo01DBConstants.seaSyphillisDate1))));
        if (cursorE.getLong(cursorE.getColumnIndex(Zpo01DBConstants.seaSyphillisDate2))>0) studyEntrySectionE.setSeaSyphillisDate2(new Date(cursorE.getLong(cursorE.getColumnIndex(Zpo01DBConstants.seaSyphillisDate2))));
        if (cursorE.getLong(cursorE.getColumnIndex(Zpo01DBConstants.seaSyphillisDate3))>0) studyEntrySectionE.setSeaSyphillisDate3(new Date(cursorE.getLong(cursorE.getColumnIndex(Zpo01DBConstants.seaSyphillisDate3))));
        studyEntrySectionE.setSeaSyphillisDoc(cursorE.getString(cursorE.getColumnIndex(Zpo01DBConstants.seaSyphillisDoc)));
        studyEntrySectionE.setSeaHiv(cursorE.getString(cursorE.getColumnIndex(Zpo01DBConstants.seaHiv)));
        if (cursorE.getLong(cursorE.getColumnIndex(Zpo01DBConstants.seaHivDate1))>0) studyEntrySectionE.setSeaHivDate1(new Date(cursorE.getLong(cursorE.getColumnIndex(Zpo01DBConstants.seaHivDate1))));
        if (cursorE.getLong(cursorE.getColumnIndex(Zpo01DBConstants.seaHivDate2))>0) studyEntrySectionE.setSeaHivDate2(new Date(cursorE.getLong(cursorE.getColumnIndex(Zpo01DBConstants.seaHivDate2))));
        if (cursorE.getLong(cursorE.getColumnIndex(Zpo01DBConstants.seaHivDate3))>0) studyEntrySectionE.setSeaHivDate3(new Date(cursorE.getLong(cursorE.getColumnIndex(Zpo01DBConstants.seaHivDate3))));
        studyEntrySectionE.setSeaHivDoc(cursorE.getString(cursorE.getColumnIndex(Zpo01DBConstants.seaHivDoc)));
        studyEntrySectionE.setSeaZika(cursorE.getString(cursorE.getColumnIndex(Zpo01DBConstants.seaZika)));
        if (cursorE.getLong(cursorE.getColumnIndex(Zpo01DBConstants.seaZikaDate1))>0) studyEntrySectionE.setSeaZikaDate1(new Date(cursorE.getLong(cursorE.getColumnIndex(Zpo01DBConstants.seaZikaDate1))));
        if (cursorE.getLong(cursorE.getColumnIndex(Zpo01DBConstants.seaZikaDate2))>0) studyEntrySectionE.setSeaZikaDate2(new Date(cursorE.getLong(cursorE.getColumnIndex(Zpo01DBConstants.seaZikaDate2))));
        if (cursorE.getLong(cursorE.getColumnIndex(Zpo01DBConstants.seaZikaDate3))>0) studyEntrySectionE.setSeaZikaDate3(new Date(cursorE.getLong(cursorE.getColumnIndex(Zpo01DBConstants.seaZikaDate3))));
        studyEntrySectionE.setSeaZikaDoc(cursorE.getString(cursorE.getColumnIndex(Zpo01DBConstants.seaZikaDoc)));
        studyEntrySectionE.setSeaChikung(cursorE.getString(cursorE.getColumnIndex(Zpo01DBConstants.seaChikung)));
        if (cursorE.getLong(cursorE.getColumnIndex(Zpo01DBConstants.seaChikungDate1))>0) studyEntrySectionE.setSeaChikungDate1(new Date(cursorE.getLong(cursorE.getColumnIndex(Zpo01DBConstants.seaChikungDate1))));
        if (cursorE.getLong(cursorE.getColumnIndex(Zpo01DBConstants.seaChikungDate2))>0) studyEntrySectionE.setSeaChikungDate2(new Date(cursorE.getLong(cursorE.getColumnIndex(Zpo01DBConstants.seaChikungDate2))));
        if (cursorE.getLong(cursorE.getColumnIndex(Zpo01DBConstants.seaChikungDate3))>0) studyEntrySectionE.setSeaChikungDate3(new Date(cursorE.getLong(cursorE.getColumnIndex(Zpo01DBConstants.seaChikungDate3))));
        studyEntrySectionE.setSeaChikungDoc(cursorE.getString(cursorE.getColumnIndex(Zpo01DBConstants.seaChikungDoc)));
        studyEntrySectionE.setSeaInfluInfect(cursorE.getString(cursorE.getColumnIndex(Zpo01DBConstants.seaInfluInfect)));
        if (cursorE.getLong(cursorE.getColumnIndex(Zpo01DBConstants.seaInflueInfectDate1))>0) studyEntrySectionE.setSeaInflueInfectDate1(new Date(cursorE.getLong(cursorE.getColumnIndex(Zpo01DBConstants.seaInflueInfectDate1))));
        if (cursorE.getLong(cursorE.getColumnIndex(Zpo01DBConstants.seaInfluInfectDate2))>0) studyEntrySectionE.setSeaInfluInfectDate2(new Date(cursorE.getLong(cursorE.getColumnIndex(Zpo01DBConstants.seaInfluInfectDate2))));
        if (cursorE.getLong(cursorE.getColumnIndex(Zpo01DBConstants.seaInfluInfectDate3))>0) studyEntrySectionE.setSeaInfluInfectDate3(new Date(cursorE.getLong(cursorE.getColumnIndex(Zpo01DBConstants.seaInfluInfectDate3))));
        studyEntrySectionE.setSeaInfluInfectDoc(cursorE.getString(cursorE.getColumnIndex(Zpo01DBConstants.seaInfluInfectDoc)));
        studyEntrySectionE.setSeaDengueInfect(cursorE.getString(cursorE.getColumnIndex(Zpo01DBConstants.seaDengueInfect)));
        if (cursorE.getLong(cursorE.getColumnIndex(Zpo01DBConstants.seaDengueInfectDate1))>0) studyEntrySectionE.setSeaDengueInfectDate1(new Date(cursorE.getLong(cursorE.getColumnIndex(Zpo01DBConstants.seaDengueInfectDate1))));
        if (cursorE.getLong(cursorE.getColumnIndex(Zpo01DBConstants.seaDengueInfectDate2))>0) studyEntrySectionE.setSeaDengueInfectDate2(new Date(cursorE.getLong(cursorE.getColumnIndex(Zpo01DBConstants.seaDengueInfectDate2))));
        if (cursorE.getLong(cursorE.getColumnIndex(Zpo01DBConstants.seaDengueInfectDate3))>0) studyEntrySectionE.setSeaDengueInfectDate3(new Date(cursorE.getLong(cursorE.getColumnIndex(Zpo01DBConstants.seaDengueInfectDate3))));
        studyEntrySectionE.setSeaDengueInfectDoc(cursorE.getString(cursorE.getColumnIndex(Zpo01DBConstants.seaDengueInfectDoc)));
        studyEntrySectionE.setSeaFeverSymptom(cursorE.getString(cursorE.getColumnIndex(Zpo01DBConstants.seaFeverSymptom)));
        studyEntrySectionE.setSeaRash(cursorE.getString(cursorE.getColumnIndex(Zpo01DBConstants.seaRash)));
        studyEntrySectionE.setSeaItch(cursorE.getString(cursorE.getColumnIndex(Zpo01DBConstants.seaItch)));
        studyEntrySectionE.setSeaRashFirst(cursorE.getString(cursorE.getColumnIndex(Zpo01DBConstants.seaRashFirst)));
        studyEntrySectionE.setSeaRashDay(cursorE.getString(cursorE.getColumnIndex(Zpo01DBConstants.seaRashDay)));
        studyEntrySectionE.setSeaRashMonth(cursorE.getString(cursorE.getColumnIndex(Zpo01DBConstants.seaRashMonth)));
        studyEntrySectionE.setSeaRashYear(cursorE.getString(cursorE.getColumnIndex(Zpo01DBConstants.seaRashYear)));
        if (cursorE.getInt(cursorE.getColumnIndex(Zpo01DBConstants.seaRashDuration))>0) studyEntrySectionE.setSeaRashDuration(cursorE.getInt(cursorE.getColumnIndex(Zpo01DBConstants.seaRashDuration)));
        studyEntrySectionE.setSeaRashSpread(cursorE.getString(cursorE.getColumnIndex(Zpo01DBConstants.seaRashSpread)));
        studyEntrySectionE.setSeaSpreadPart(cursorE.getString(cursorE.getColumnIndex(Zpo01DBConstants.seaSpreadPart)));
        studyEntrySectionE.setSeaFeverExperience(cursorE.getString(cursorE.getColumnIndex(Zpo01DBConstants.seaFeverExperience)));
        studyEntrySectionE.setSeaTempMeasure(cursorE.getString(cursorE.getColumnIndex(Zpo01DBConstants.seaTempMeasure)));
        if (cursorE.getFloat(cursorE.getColumnIndex(Zpo01DBConstants.seaHighTemp))>0) studyEntrySectionE.setSeaHighTemp(cursorE.getFloat(cursorE.getColumnIndex(Zpo01DBConstants.seaHighTemp)));
        studyEntrySectionE.setSeaHightemUnit(cursorE.getString(cursorE.getColumnIndex(Zpo01DBConstants.seaHightemUnit)));
        studyEntrySectionE.setSeaTempunknown(cursorE.getString(cursorE.getColumnIndex(Zpo01DBConstants.seaTempunknown)));
        studyEntrySectionE.setSeaFeverDay(cursorE.getString(cursorE.getColumnIndex(Zpo01DBConstants.seaFeverDay)));
        studyEntrySectionE.setSeaFeverMonth(cursorE.getString(cursorE.getColumnIndex(Zpo01DBConstants.seaFeverMonth)));
        studyEntrySectionE.setSeaFeverYear(cursorE.getString(cursorE.getColumnIndex(Zpo01DBConstants.seaFeverYear)));
        if (cursorE.getInt(cursorE.getColumnIndex(Zpo01DBConstants.seaFeverDuration))>0) studyEntrySectionE.setSeaFeverDuration(cursorE.getInt(cursorE.getColumnIndex(Zpo01DBConstants.seaFeverDuration)));
        studyEntrySectionE.setSeaFDurationunknown(cursorE.getString(cursorE.getColumnIndex(Zpo01DBConstants.seaFDurationunknown)));
        studyEntrySectionE.setSeaRedeyes(cursorE.getString(cursorE.getColumnIndex(Zpo01DBConstants.seaRedeyes)));
        studyEntrySectionE.setSeaRedeyesDay(cursorE.getString(cursorE.getColumnIndex(Zpo01DBConstants.seaRedeyesDay)));
        studyEntrySectionE.setSeaRedeyesMonth(cursorE.getString(cursorE.getColumnIndex(Zpo01DBConstants.seaRedeyesMonth)));
        studyEntrySectionE.setSeaRedeyesYear(cursorE.getString(cursorE.getColumnIndex(Zpo01DBConstants.seaRedeyesYear)));
        if (cursorE.getInt(cursorE.getColumnIndex(Zpo01DBConstants.seaRedeyesDuration))>0) studyEntrySectionE.setSeaRedeyesDuration(cursorE.getInt(cursorE.getColumnIndex(Zpo01DBConstants.seaRedeyesDuration)));
        studyEntrySectionE.setSeaOccurSame(cursorE.getString(cursorE.getColumnIndex(Zpo01DBConstants.seaOccurSame)));
        studyEntrySectionE.setSeaSameSymptom(cursorE.getString(cursorE.getColumnIndex(Zpo01DBConstants.seaSameSymptom)));
        studyEntrySectionE.setSeaJoint(cursorE.getString(cursorE.getColumnIndex(Zpo01DBConstants.seaJoint)));
        studyEntrySectionE.setSeaJointDay(cursorE.getString(cursorE.getColumnIndex(Zpo01DBConstants.seaJointDay)));
        studyEntrySectionE.setSeaJointMonth(cursorE.getString(cursorE.getColumnIndex(Zpo01DBConstants.seaJointMonth)));
        studyEntrySectionE.setSeaJointYear(cursorE.getString(cursorE.getColumnIndex(Zpo01DBConstants.seaJointYear)));
        if (cursorE.getInt(cursorE.getColumnIndex(Zpo01DBConstants.seaJointDuration))>0) studyEntrySectionE.setSeaJointDuration(cursorE.getInt(cursorE.getColumnIndex(Zpo01DBConstants.seaJointDuration)));
        studyEntrySectionE.setSeaHeadache(cursorE.getString(cursorE.getColumnIndex(Zpo01DBConstants.seaHeadache)));
        studyEntrySectionE.setSeaHeadacheDay(cursorE.getString(cursorE.getColumnIndex(Zpo01DBConstants.seaHeadacheDay)));
        studyEntrySectionE.setSeaHeadacheMonth(cursorE.getString(cursorE.getColumnIndex(Zpo01DBConstants.seaHeadacheMonth)));
        studyEntrySectionE.setSeaHeadacheYear(cursorE.getString(cursorE.getColumnIndex(Zpo01DBConstants.seaHeadacheYear)));
        if (cursorE.getInt(cursorE.getColumnIndex(Zpo01DBConstants.seaHeadacheDuration))>0) studyEntrySectionE.setSeaHeadacheDuration(cursorE.getInt(cursorE.getColumnIndex(Zpo01DBConstants.seaHeadacheDuration)));
        studyEntrySectionE.setSeaSymptomOther(cursorE.getString(cursorE.getColumnIndex(Zpo01DBConstants.seaSymptomOther)));
        studyEntrySectionE.setSeaSpecifySymptom(cursorE.getString(cursorE.getColumnIndex(Zpo01DBConstants.seaSpecifySymptom)));
        studyEntrySectionE.setSeaOtherSymptom(cursorE.getString(cursorE.getColumnIndex(Zpo01DBConstants.seaOtherSymptom)));
        studyEntrySectionE.setSeaMedicare(cursorE.getString(cursorE.getColumnIndex(Zpo01DBConstants.seaMedicare)));
        studyEntrySectionE.setSeaCareDay(cursorE.getString(cursorE.getColumnIndex(Zpo01DBConstants.seaCareDay)));
        studyEntrySectionE.setSeaCareMonth(cursorE.getString(cursorE.getColumnIndex(Zpo01DBConstants.seaCareMonth)));
        studyEntrySectionE.setSeaCareYear(cursorE.getString(cursorE.getColumnIndex(Zpo01DBConstants.seaCareYear)));
        studyEntrySectionE.setSeaCareFacility(cursorE.getString(cursorE.getColumnIndex(Zpo01DBConstants.seaCareFacility)));
        studyEntrySectionE.setSeaHospitalized(cursorE.getString(cursorE.getColumnIndex(Zpo01DBConstants.seaHospitalized)));
        studyEntrySectionE.setSeaHospital(cursorE.getString(cursorE.getColumnIndex(Zpo01DBConstants.seaHospital)));
        studyEntrySectionE.setSeaDiagRubella(cursorE.getString(cursorE.getColumnIndex(Zpo01DBConstants.seaDiagRubella)));
        studyEntrySectionE.setSeaDiagDengue(cursorE.getString(cursorE.getColumnIndex(Zpo01DBConstants.seaDiagDengue)));
        studyEntrySectionE.setSeaDiagChikung(cursorE.getString(cursorE.getColumnIndex(Zpo01DBConstants.seaDiagChikung)));
        studyEntrySectionE.setSeaDiagZika(cursorE.getString(cursorE.getColumnIndex(Zpo01DBConstants.seaDiagZika)));
        studyEntrySectionE.setSeaDiagCytome(cursorE.getString(cursorE.getColumnIndex(Zpo01DBConstants.seaDiagCytome)));
        studyEntrySectionE.setSeaMedicine(cursorE.getString(cursorE.getColumnIndex(Zpo01DBConstants.seaMedicine)));
        studyEntrySectionE.setSeaMedcineName(cursorE.getString(cursorE.getColumnIndex(Zpo01DBConstants.seaMedcineName)));
        studyEntrySectionE.setSeaGuillainbarre(cursorE.getString(cursorE.getColumnIndex(Zpo01DBConstants.seaGuillainbarre)));
        studyEntrySectionE.setSeaTingling(cursorE.getString(cursorE.getColumnIndex(Zpo01DBConstants.seaTingling)));
        studyEntrySectionE.setSeaTinglingArm(cursorE.getString(cursorE.getColumnIndex(Zpo01DBConstants.seaTinglingArm)));
        studyEntrySectionE.setSeaTinglingLeg(cursorE.getString(cursorE.getColumnIndex(Zpo01DBConstants.seaTinglingLeg)));
        studyEntrySectionE.setSeaTinglingHand(cursorE.getString(cursorE.getColumnIndex(Zpo01DBConstants.seaTinglingHand)));
        studyEntrySectionE.setSeaTinglingFoot(cursorE.getString(cursorE.getColumnIndex(Zpo01DBConstants.seaTinglingFoot)));
        studyEntrySectionE.setSeaTinglingFace(cursorE.getString(cursorE.getColumnIndex(Zpo01DBConstants.seaTinglingFace)));
        studyEntrySectionE.setSeaTinglingOther(cursorE.getString(cursorE.getColumnIndex(Zpo01DBConstants.seaTinglingOther)));
        studyEntrySectionE.setSeaSensationMin(cursorE.getString(cursorE.getColumnIndex(Zpo01DBConstants.seaSensationMin)));
        studyEntrySectionE.setSeaSensationHr(cursorE.getString(cursorE.getColumnIndex(Zpo01DBConstants.seaSensationHr)));
        studyEntrySectionE.setSeaSenstaionDay(cursorE.getString(cursorE.getColumnIndex(Zpo01DBConstants.seaSenstaionDay)));
        studyEntrySectionE.setSeaInjury(cursorE.getString(cursorE.getColumnIndex(Zpo01DBConstants.seaInjury)));
        studyEntrySectionE.setSeaTinglingDay(cursorE.getString(cursorE.getColumnIndex(Zpo01DBConstants.seaTinglingDay)));
        studyEntrySectionE.setSeaTinglingMonth(cursorE.getString(cursorE.getColumnIndex(Zpo01DBConstants.seaTinglingMonth)));
        studyEntrySectionE.setSeaTinglingYear(cursorE.getString(cursorE.getColumnIndex(Zpo01DBConstants.seaTinglingYear)));
        if (cursorE.getInt(cursorE.getColumnIndex(Zpo01DBConstants.seaTinglingDuration))>0) studyEntrySectionE.setSeaTinglingDuration(cursorE.getInt(cursorE.getColumnIndex(Zpo01DBConstants.seaTinglingDuration)));
        studyEntrySectionE.setSeaNumbness(cursorE.getString(cursorE.getColumnIndex(Zpo01DBConstants.seaNumbness)));
        studyEntrySectionE.setSeaNumbArm(cursorE.getString(cursorE.getColumnIndex(Zpo01DBConstants.seaNumbArm)));
        studyEntrySectionE.setSeaNumbLeg(cursorE.getString(cursorE.getColumnIndex(Zpo01DBConstants.seaNumbLeg)));
        studyEntrySectionE.setSeaNumbHand(cursorE.getString(cursorE.getColumnIndex(Zpo01DBConstants.seaNumbHand)));
        studyEntrySectionE.setSeaNumbFoot(cursorE.getString(cursorE.getColumnIndex(Zpo01DBConstants.seaNumbFoot)));
        studyEntrySectionE.setSeaNumbFace(cursorE.getString(cursorE.getColumnIndex(Zpo01DBConstants.seaNumbFace)));
        studyEntrySectionE.setSeaNumbOther(cursorE.getString(cursorE.getColumnIndex(Zpo01DBConstants.seaNumbOther)));
        studyEntrySectionE.setSeaNumbDay(cursorE.getString(cursorE.getColumnIndex(Zpo01DBConstants.seaNumbDay)));
        studyEntrySectionE.setSeaNumbMonth(cursorE.getString(cursorE.getColumnIndex(Zpo01DBConstants.seaNumbMonth)));
        studyEntrySectionE.setSeaNumbYear(cursorE.getString(cursorE.getColumnIndex(Zpo01DBConstants.seaNumbYear)));
        if (cursorE.getInt(cursorE.getColumnIndex(Zpo01DBConstants.seaNumbDuration))>0) studyEntrySectionE.setSeaNumbDuration(cursorE.getInt(cursorE.getColumnIndex(Zpo01DBConstants.seaNumbDuration)));
        studyEntrySectionE.setSeaParalysis(cursorE.getString(cursorE.getColumnIndex(Zpo01DBConstants.seaParalysis)));
        studyEntrySectionE.setSeaParaArm(cursorE.getString(cursorE.getColumnIndex(Zpo01DBConstants.seaParaArm)));
        studyEntrySectionE.setSeaParaLeg(cursorE.getString(cursorE.getColumnIndex(Zpo01DBConstants.seaParaLeg)));
        studyEntrySectionE.setSeaParaHand(cursorE.getString(cursorE.getColumnIndex(Zpo01DBConstants.seaParaHand)));
        studyEntrySectionE.setSeaParaFoot(cursorE.getString(cursorE.getColumnIndex(Zpo01DBConstants.seaParaFoot)));
        studyEntrySectionE.setSeaParaFace(cursorE.getString(cursorE.getColumnIndex(Zpo01DBConstants.seaParaFace)));
        studyEntrySectionE.setSeaParaOther(cursorE.getString(cursorE.getColumnIndex(Zpo01DBConstants.seaParaOther)));
        studyEntrySectionE.setSeaParaDay(cursorE.getString(cursorE.getColumnIndex(Zpo01DBConstants.seaParaDay)));
        studyEntrySectionE.setSeaParaMonth(cursorE.getString(cursorE.getColumnIndex(Zpo01DBConstants.seaParaMonth)));
        studyEntrySectionE.setSeaParaYear(cursorE.getString(cursorE.getColumnIndex(Zpo01DBConstants.seaParaYear)));
        if (cursorE.getInt(cursorE.getColumnIndex(Zpo01DBConstants.seaParaDuration))>0) studyEntrySectionE.setSeaParaDuration(cursorE.getInt(cursorE.getColumnIndex(Zpo01DBConstants.seaParaDuration)));
        //Movil y Metadata
        if(cursorE.getLong(cursorE.getColumnIndex(MainDBConstants.recordDate))>0) studyEntrySectionE.setRecordDate(new Date(cursorE.getLong(cursorE.getColumnIndex(MainDBConstants.recordDate))));
        studyEntrySectionE.setRecordUser(cursorE.getString(cursorE.getColumnIndex(MainDBConstants.recordUser)));
        studyEntrySectionE.setPasive(cursorE.getString(cursorE.getColumnIndex(MainDBConstants.pasive)).charAt(0));
        studyEntrySectionE.setIdInstancia(cursorE.getInt(cursorE.getColumnIndex(MainDBConstants.ID_INSTANCIA)));
        studyEntrySectionE.setInstancePath(cursorE.getString(cursorE.getColumnIndex(MainDBConstants.FILE_PATH)));
        studyEntrySectionE.setEstado(cursorE.getString(cursorE.getColumnIndex(MainDBConstants.STATUS)));
        studyEntrySectionE.setStart(cursorE.getString(cursorE.getColumnIndex(MainDBConstants.START)));
        studyEntrySectionE.setEnd(cursorE.getString(cursorE.getColumnIndex(MainDBConstants.END)));
        studyEntrySectionE.setSimserial(cursorE.getString(cursorE.getColumnIndex(MainDBConstants.SIM_SERIAL)));
        studyEntrySectionE.setPhonenumber(cursorE.getString(cursorE.getColumnIndex(MainDBConstants.PHONE_NUMBER)));
        studyEntrySectionE.setDeviceid(cursorE.getString(cursorE.getColumnIndex(MainDBConstants.DEVICE_ID)));
        if(cursorE.getLong(cursorE.getColumnIndex(MainDBConstants.TODAY))>0) studyEntrySectionE.setToday(new Date(cursorE.getLong(cursorE.getColumnIndex(MainDBConstants.TODAY))));

        return studyEntrySectionE;
    }

    /**********************************************************/
    /********** PARA OBJETO Zpo01StudyEntrySectionDtoF *********/
    /**********************************************************/
    public static ContentValues crearZpo01StudyEntrySectionDtoFValues(Zpo01StudyEntrySectionDtoF studyEntrySectionFtoK){
        ContentValues cv = new ContentValues();
        cv.put(Zpo01DBConstants.recordId,studyEntrySectionFtoK.getRecordId());
        cv.put(Zpo01DBConstants.eventName, studyEntrySectionFtoK.getEventName());
        cv.put(Zpo01DBConstants.seaPreg,studyEntrySectionFtoK.getSeaPreg());
        cv.put(Zpo01DBConstants.seaFirstPreg,studyEntrySectionFtoK.getSeaFirstPreg());
        cv.put(Zpo01DBConstants.seaAnemia,studyEntrySectionFtoK.getSeaAnemia());
        cv.put(Zpo01DBConstants.seaVaginal,studyEntrySectionFtoK.getSeaVaginal());
        cv.put(Zpo01DBConstants.seaUtiPrior,studyEntrySectionFtoK.getSeaUtiPrior());
        cv.put(Zpo01DBConstants.seaSexually,studyEntrySectionFtoK.getSeaSexually());
        cv.put(Zpo01DBConstants.seaPreterm,studyEntrySectionFtoK.getSeaPreterm());
        cv.put(Zpo01DBConstants.seaPreeclampsia,studyEntrySectionFtoK.getSeaPreeclampsia());
        cv.put(Zpo01DBConstants.seaEclampsia,studyEntrySectionFtoK.getSeaEclampsia());
        cv.put(Zpo01DBConstants.seaHeart,studyEntrySectionFtoK.getSeaHeart());
        cv.put(Zpo01DBConstants.seaNeuropathy,studyEntrySectionFtoK.getSeaNeuropathy());
        cv.put(Zpo01DBConstants.seaGestational,studyEntrySectionFtoK.getSeaGestational());
        cv.put(Zpo01DBConstants.seaTotalPreg,studyEntrySectionFtoK.getSeaTotalPreg());
        if (studyEntrySectionFtoK.getSeaDeliveryDate1()!=null) cv.put(Zpo01DBConstants.seaDeliveryDate1,studyEntrySectionFtoK.getSeaDeliveryDate1().getTime());
        cv.put(Zpo01DBConstants.seaGage1,studyEntrySectionFtoK.getSeaGage1());
        cv.put(Zpo01DBConstants.seaOutcome1,studyEntrySectionFtoK.getSeaOutcome1());
        cv.put(Zpo01DBConstants.seaBdefects1,studyEntrySectionFtoK.getSeaBdefects1());
        if (studyEntrySectionFtoK.getSeaDeliveryDate2()!=null) cv.put(Zpo01DBConstants.seaDeliveryDate2,studyEntrySectionFtoK.getSeaDeliveryDate2().getTime());
        cv.put(Zpo01DBConstants.seaGage2,studyEntrySectionFtoK.getSeaGage2());
        cv.put(Zpo01DBConstants.seaOutcome2,studyEntrySectionFtoK.getSeaOutcome2());
        cv.put(Zpo01DBConstants.seaBdefects2,studyEntrySectionFtoK.getSeaBdefects2());
        if (studyEntrySectionFtoK.getSeaDeliveryDate3()!=null) cv.put(Zpo01DBConstants.seaDeliveryDate3,studyEntrySectionFtoK.getSeaDeliveryDate3().getTime());
        cv.put(Zpo01DBConstants.seaGage3,studyEntrySectionFtoK.getSeaGage3());
        cv.put(Zpo01DBConstants.seaOutcome3,studyEntrySectionFtoK.getSeaOutcome3());
        cv.put(Zpo01DBConstants.seaBdefects3,studyEntrySectionFtoK.getSeaBdefects3());
        if (studyEntrySectionFtoK.getSeaDeliveryDate4()!=null) cv.put(Zpo01DBConstants.seaDeliveryDate4,studyEntrySectionFtoK.getSeaDeliveryDate4().getTime());
        cv.put(Zpo01DBConstants.seaGage4,studyEntrySectionFtoK.getSeaGage4());
        cv.put(Zpo01DBConstants.seaOutcome4,studyEntrySectionFtoK.getSeaOutcome4());
        cv.put(Zpo01DBConstants.seaBdefects4,studyEntrySectionFtoK.getSeaBdefects4());
        if (studyEntrySectionFtoK.getSeaDeliveryDate5()!=null) cv.put(Zpo01DBConstants.seaDeliveryDate5,studyEntrySectionFtoK.getSeaDeliveryDate5().getTime());
        cv.put(Zpo01DBConstants.seaGage5,studyEntrySectionFtoK.getSeaGage5());
        cv.put(Zpo01DBConstants.seaOutcome5,studyEntrySectionFtoK.getSeaOutcome5());
        cv.put(Zpo01DBConstants.seaBdefects5,studyEntrySectionFtoK.getSeaBdefects5());
        if (studyEntrySectionFtoK.getSeaDeliveryDate6()!=null) cv.put(Zpo01DBConstants.seaDeliveryDate6,studyEntrySectionFtoK.getSeaDeliveryDate6().getTime());
        cv.put(Zpo01DBConstants.seaGage6,studyEntrySectionFtoK.getSeaGage6());
        cv.put(Zpo01DBConstants.seaOutcome6,studyEntrySectionFtoK.getSeaOutcome6());
        cv.put(Zpo01DBConstants.seaBdefects6,studyEntrySectionFtoK.getSeaBdefects6());
        cv.put(Zpo01DBConstants.seaPersisHeadache,studyEntrySectionFtoK.getSeaPersisHeadache());
        cv.put(Zpo01DBConstants.seaDizziness,studyEntrySectionFtoK.getSeaDizziness());
        cv.put(Zpo01DBConstants.seaNausea,studyEntrySectionFtoK.getSeaNausea());
        cv.put(Zpo01DBConstants.seaVomiting,studyEntrySectionFtoK.getSeaVomiting());
        cv.put(Zpo01DBConstants.seaSeeingLights,studyEntrySectionFtoK.getSeaSeeingLights());
        cv.put(Zpo01DBConstants.seaSpecifyType,studyEntrySectionFtoK.getSeaSpecifyType());
        cv.put(Zpo01DBConstants.seaSwelling,studyEntrySectionFtoK.getSeaSwelling());
        cv.put(Zpo01DBConstants.seaFetalMov,studyEntrySectionFtoK.getSeaFetalMov());
        cv.put(Zpo01DBConstants.seaContraction,studyEntrySectionFtoK.getSeaContraction());
        cv.put(Zpo01DBConstants.seaFreqWeek,studyEntrySectionFtoK.getSeaFreqWeek());
        cv.put(Zpo01DBConstants.seaFreqDay,studyEntrySectionFtoK.getSeaFreqDay());
        cv.put(Zpo01DBConstants.seaFreqHour,studyEntrySectionFtoK.getSeaFreqHour());
        cv.put(Zpo01DBConstants.seaFreqMin,studyEntrySectionFtoK.getSeaFreqMin());
        cv.put(Zpo01DBConstants.seaVagiDischarge,studyEntrySectionFtoK.getSeaVagiDischarge());
        cv.put(Zpo01DBConstants.seaCharacterDisch,studyEntrySectionFtoK.getSeaCharacterDisch());
        cv.put(Zpo01DBConstants.seaBleeding,studyEntrySectionFtoK.getSeaBleeding());
        cv.put(Zpo01DBConstants.seaYesBleeding,studyEntrySectionFtoK.getSeaYesBleeding());
        cv.put(Zpo01DBConstants.seaUti,studyEntrySectionFtoK.getSeaUti());
        if (studyEntrySectionFtoK.getSeaPrenatalCare()!=null) cv.put(Zpo01DBConstants.seaPrenatalCare,studyEntrySectionFtoK.getSeaPrenatalCare().getTime());
        cv.put(Zpo01DBConstants.seaMutiv,studyEntrySectionFtoK.getSeaMutiv());
        cv.put(Zpo01DBConstants.seaIron,studyEntrySectionFtoK.getSeaIron());
        cv.put(Zpo01DBConstants.seaOften,studyEntrySectionFtoK.getSeaOften());
        cv.put(Zpo01DBConstants.seaIdCompleting,studyEntrySectionFtoK.getSeaIdCompleting());
        if (studyEntrySectionFtoK.getSeaDateCompleted()!=null) cv.put(Zpo01DBConstants.seaDateCompleted,studyEntrySectionFtoK.getSeaDateCompleted().getTime());
        cv.put(Zpo01DBConstants.seaIdReviewer,studyEntrySectionFtoK.getSeaIdReviewer());
        if (studyEntrySectionFtoK.getSeaDateReviewed()!=null) cv.put(Zpo01DBConstants.seaDateReviewed,studyEntrySectionFtoK.getSeaDateReviewed().getTime());
        cv.put(Zpo01DBConstants.seaIdDataEntry,studyEntrySectionFtoK.getSeaIdDataEntry());
        if (studyEntrySectionFtoK.getSeaDateEntered()!=null) cv.put(Zpo01DBConstants.seaDateEntered,studyEntrySectionFtoK.getSeaDateEntered().getTime());

        if (studyEntrySectionFtoK.getRecordDate() != null) cv.put(MainDBConstants.recordDate, studyEntrySectionFtoK.getRecordDate().getTime());
        cv.put(MainDBConstants.recordUser, studyEntrySectionFtoK.getRecordUser());
        cv.put(MainDBConstants.pasive, String.valueOf(studyEntrySectionFtoK.getPasive()));
        cv.put(MainDBConstants.ID_INSTANCIA, studyEntrySectionFtoK.getIdInstancia());
        cv.put(MainDBConstants.FILE_PATH, studyEntrySectionFtoK.getInstancePath());
        cv.put(MainDBConstants.STATUS, studyEntrySectionFtoK.getEstado());
        cv.put(MainDBConstants.START, studyEntrySectionFtoK.getStart());
        cv.put(MainDBConstants.END, studyEntrySectionFtoK.getEnd());
        cv.put(MainDBConstants.DEVICE_ID, studyEntrySectionFtoK.getDeviceid());
        cv.put(MainDBConstants.SIM_SERIAL, studyEntrySectionFtoK.getSimserial());
        cv.put(MainDBConstants.PHONE_NUMBER, studyEntrySectionFtoK.getPhonenumber());
        if (studyEntrySectionFtoK.getToday() != null) cv.put(MainDBConstants.TODAY, studyEntrySectionFtoK.getToday().getTime());
        return cv;
    }

    public static Zpo01StudyEntrySectionDtoF crearZpo01StudyEntrySectionDtoF(Cursor cursorFtoK){
        Zpo01StudyEntrySectionDtoF studyEntrySectionFtoK = new Zpo01StudyEntrySectionDtoF();
        studyEntrySectionFtoK.setRecordId(cursorFtoK.getString(cursorFtoK.getColumnIndex(Zpo01DBConstants.recordId)));
        studyEntrySectionFtoK.setEventName(cursorFtoK.getString(cursorFtoK.getColumnIndex(Zpo01DBConstants.eventName)));
        studyEntrySectionFtoK.setSeaPreg(cursorFtoK.getString(cursorFtoK.getColumnIndex(Zpo01DBConstants.seaPreg)));
        studyEntrySectionFtoK.setSeaFirstPreg(cursorFtoK.getString(cursorFtoK.getColumnIndex(Zpo01DBConstants.seaFirstPreg)));
        studyEntrySectionFtoK.setSeaAnemia(cursorFtoK.getString(cursorFtoK.getColumnIndex(Zpo01DBConstants.seaAnemia)));
        studyEntrySectionFtoK.setSeaVaginal(cursorFtoK.getString(cursorFtoK.getColumnIndex(Zpo01DBConstants.seaVaginal)));
        studyEntrySectionFtoK.setSeaUtiPrior(cursorFtoK.getString(cursorFtoK.getColumnIndex(Zpo01DBConstants.seaUtiPrior)));
        studyEntrySectionFtoK.setSeaSexually(cursorFtoK.getString(cursorFtoK.getColumnIndex(Zpo01DBConstants.seaSexually)));
        studyEntrySectionFtoK.setSeaPreterm(cursorFtoK.getString(cursorFtoK.getColumnIndex(Zpo01DBConstants.seaPreterm)));
        studyEntrySectionFtoK.setSeaPreeclampsia(cursorFtoK.getString(cursorFtoK.getColumnIndex(Zpo01DBConstants.seaPreeclampsia)));
        studyEntrySectionFtoK.setSeaEclampsia(cursorFtoK.getString(cursorFtoK.getColumnIndex(Zpo01DBConstants.seaEclampsia)));
        studyEntrySectionFtoK.setSeaHeart(cursorFtoK.getString(cursorFtoK.getColumnIndex(Zpo01DBConstants.seaHeart)));
        studyEntrySectionFtoK.setSeaNeuropathy(cursorFtoK.getString(cursorFtoK.getColumnIndex(Zpo01DBConstants.seaNeuropathy)));
        studyEntrySectionFtoK.setSeaGestational(cursorFtoK.getString(cursorFtoK.getColumnIndex(Zpo01DBConstants.seaGestational)));
        if (cursorFtoK.getInt(cursorFtoK.getColumnIndex(Zpo01DBConstants.seaTotalPreg))>0) studyEntrySectionFtoK.setSeaTotalPreg(cursorFtoK.getInt(cursorFtoK.getColumnIndex(Zpo01DBConstants.seaTotalPreg)));
        if (cursorFtoK.getLong(cursorFtoK.getColumnIndex(Zpo01DBConstants.seaDeliveryDate1))>0) studyEntrySectionFtoK.setSeaDeliveryDate1(new Date(cursorFtoK.getLong(cursorFtoK.getColumnIndex(Zpo01DBConstants.seaDeliveryDate1))));
        if (cursorFtoK.getInt(cursorFtoK.getColumnIndex(Zpo01DBConstants.seaGage1))>0) studyEntrySectionFtoK.setSeaGage1(cursorFtoK.getInt(cursorFtoK.getColumnIndex(Zpo01DBConstants.seaGage1)));
        studyEntrySectionFtoK.setSeaOutcome1(cursorFtoK.getString(cursorFtoK.getColumnIndex(Zpo01DBConstants.seaOutcome1)));
        studyEntrySectionFtoK.setSeaBdefects1(cursorFtoK.getString(cursorFtoK.getColumnIndex(Zpo01DBConstants.seaBdefects1)));
        if (cursorFtoK.getLong(cursorFtoK.getColumnIndex(Zpo01DBConstants.seaDeliveryDate2))>0) studyEntrySectionFtoK.setSeaDeliveryDate2(new Date(cursorFtoK.getLong(cursorFtoK.getColumnIndex(Zpo01DBConstants.seaDeliveryDate2))));
        if (cursorFtoK.getInt(cursorFtoK.getColumnIndex(Zpo01DBConstants.seaGage2))>0) studyEntrySectionFtoK.setSeaGage2(cursorFtoK.getInt(cursorFtoK.getColumnIndex(Zpo01DBConstants.seaGage2)));
        studyEntrySectionFtoK.setSeaOutcome2(cursorFtoK.getString(cursorFtoK.getColumnIndex(Zpo01DBConstants.seaOutcome2)));
        studyEntrySectionFtoK.setSeaBdefects2(cursorFtoK.getString(cursorFtoK.getColumnIndex(Zpo01DBConstants.seaBdefects2)));
        if (cursorFtoK.getLong(cursorFtoK.getColumnIndex(Zpo01DBConstants.seaDeliveryDate3))>0) studyEntrySectionFtoK.setSeaDeliveryDate3(new Date(cursorFtoK.getLong(cursorFtoK.getColumnIndex(Zpo01DBConstants.seaDeliveryDate3))));
        if (cursorFtoK.getInt(cursorFtoK.getColumnIndex(Zpo01DBConstants.seaGage3))>0) studyEntrySectionFtoK.setSeaGage3(cursorFtoK.getInt(cursorFtoK.getColumnIndex(Zpo01DBConstants.seaGage3)));
        studyEntrySectionFtoK.setSeaOutcome3(cursorFtoK.getString(cursorFtoK.getColumnIndex(Zpo01DBConstants.seaOutcome3)));
        studyEntrySectionFtoK.setSeaBdefects3(cursorFtoK.getString(cursorFtoK.getColumnIndex(Zpo01DBConstants.seaBdefects3)));
        if (cursorFtoK.getLong(cursorFtoK.getColumnIndex(Zpo01DBConstants.seaDeliveryDate4))>0) studyEntrySectionFtoK.setSeaDeliveryDate4(new Date(cursorFtoK.getLong(cursorFtoK.getColumnIndex(Zpo01DBConstants.seaDeliveryDate4))));
        if (cursorFtoK.getInt(cursorFtoK.getColumnIndex(Zpo01DBConstants.seaGage4))>0) studyEntrySectionFtoK.setSeaGage4(cursorFtoK.getInt(cursorFtoK.getColumnIndex(Zpo01DBConstants.seaGage4)));
        studyEntrySectionFtoK.setSeaOutcome4(cursorFtoK.getString(cursorFtoK.getColumnIndex(Zpo01DBConstants.seaOutcome4)));
        studyEntrySectionFtoK.setSeaBdefects4(cursorFtoK.getString(cursorFtoK.getColumnIndex(Zpo01DBConstants.seaBdefects4)));
        if (cursorFtoK.getLong(cursorFtoK.getColumnIndex(Zpo01DBConstants.seaDeliveryDate5))>0) studyEntrySectionFtoK.setSeaDeliveryDate5(new Date(cursorFtoK.getLong(cursorFtoK.getColumnIndex(Zpo01DBConstants.seaDeliveryDate5))));
        if (cursorFtoK.getInt(cursorFtoK.getColumnIndex(Zpo01DBConstants.seaGage5))>0) studyEntrySectionFtoK.setSeaGage5(cursorFtoK.getInt(cursorFtoK.getColumnIndex(Zpo01DBConstants.seaGage5)));
        studyEntrySectionFtoK.setSeaOutcome5(cursorFtoK.getString(cursorFtoK.getColumnIndex(Zpo01DBConstants.seaOutcome5)));
        studyEntrySectionFtoK.setSeaBdefects5(cursorFtoK.getString(cursorFtoK.getColumnIndex(Zpo01DBConstants.seaBdefects5)));
        if (cursorFtoK.getLong(cursorFtoK.getColumnIndex(Zpo01DBConstants.seaDeliveryDate6))>0) studyEntrySectionFtoK.setSeaDeliveryDate6(new Date(cursorFtoK.getLong(cursorFtoK.getColumnIndex(Zpo01DBConstants.seaDeliveryDate6))));
        if (cursorFtoK.getInt(cursorFtoK.getColumnIndex(Zpo01DBConstants.seaGage6))>0) studyEntrySectionFtoK.setSeaGage6(cursorFtoK.getInt(cursorFtoK.getColumnIndex(Zpo01DBConstants.seaGage6)));
        studyEntrySectionFtoK.setSeaOutcome6(cursorFtoK.getString(cursorFtoK.getColumnIndex(Zpo01DBConstants.seaOutcome6)));
        studyEntrySectionFtoK.setSeaBdefects6(cursorFtoK.getString(cursorFtoK.getColumnIndex(Zpo01DBConstants.seaBdefects6)));
        studyEntrySectionFtoK.setSeaPersisHeadache(cursorFtoK.getString(cursorFtoK.getColumnIndex(Zpo01DBConstants.seaPersisHeadache)));
        studyEntrySectionFtoK.setSeaDizziness(cursorFtoK.getString(cursorFtoK.getColumnIndex(Zpo01DBConstants.seaDizziness)));
        studyEntrySectionFtoK.setSeaNausea(cursorFtoK.getString(cursorFtoK.getColumnIndex(Zpo01DBConstants.seaNausea)));
        studyEntrySectionFtoK.setSeaVomiting(cursorFtoK.getString(cursorFtoK.getColumnIndex(Zpo01DBConstants.seaVomiting)));
        studyEntrySectionFtoK.setSeaSeeingLights(cursorFtoK.getString(cursorFtoK.getColumnIndex(Zpo01DBConstants.seaSeeingLights)));
        studyEntrySectionFtoK.setSeaSpecifyType(cursorFtoK.getString(cursorFtoK.getColumnIndex(Zpo01DBConstants.seaSpecifyType)));
        studyEntrySectionFtoK.setSeaSwelling(cursorFtoK.getString(cursorFtoK.getColumnIndex(Zpo01DBConstants.seaSwelling)));
        studyEntrySectionFtoK.setSeaFetalMov(cursorFtoK.getString(cursorFtoK.getColumnIndex(Zpo01DBConstants.seaFetalMov)));
        studyEntrySectionFtoK.setSeaContraction(cursorFtoK.getString(cursorFtoK.getColumnIndex(Zpo01DBConstants.seaContraction)));
        if (cursorFtoK.getInt(cursorFtoK.getColumnIndex(Zpo01DBConstants.seaFreqWeek))>0) studyEntrySectionFtoK.setSeaFreqWeek(cursorFtoK.getInt(cursorFtoK.getColumnIndex(Zpo01DBConstants.seaFreqWeek)));
        if (cursorFtoK.getInt(cursorFtoK.getColumnIndex(Zpo01DBConstants.seaFreqDay))>0) studyEntrySectionFtoK.setSeaFreqDay(cursorFtoK.getInt(cursorFtoK.getColumnIndex(Zpo01DBConstants.seaFreqDay)));
        if (cursorFtoK.getInt(cursorFtoK.getColumnIndex(Zpo01DBConstants.seaFreqHour))>0) studyEntrySectionFtoK.setSeaFreqHour(cursorFtoK.getInt(cursorFtoK.getColumnIndex(Zpo01DBConstants.seaFreqHour)));
        if (cursorFtoK.getInt(cursorFtoK.getColumnIndex(Zpo01DBConstants.seaFreqMin))>0) studyEntrySectionFtoK.setSeaFreqMin(cursorFtoK.getInt(cursorFtoK.getColumnIndex(Zpo01DBConstants.seaFreqMin)));
        studyEntrySectionFtoK.setSeaVagiDischarge(cursorFtoK.getString(cursorFtoK.getColumnIndex(Zpo01DBConstants.seaVagiDischarge)));
        studyEntrySectionFtoK.setSeaCharacterDisch(cursorFtoK.getString(cursorFtoK.getColumnIndex(Zpo01DBConstants.seaCharacterDisch)));
        studyEntrySectionFtoK.setSeaBleeding(cursorFtoK.getString(cursorFtoK.getColumnIndex(Zpo01DBConstants.seaBleeding)));
        studyEntrySectionFtoK.setSeaYesBleeding(cursorFtoK.getString(cursorFtoK.getColumnIndex(Zpo01DBConstants.seaYesBleeding)));
        studyEntrySectionFtoK.setSeaUti(cursorFtoK.getString(cursorFtoK.getColumnIndex(Zpo01DBConstants.seaUti)));
        if (cursorFtoK.getLong(cursorFtoK.getColumnIndex(Zpo01DBConstants.seaPrenatalCare))>0) studyEntrySectionFtoK.setSeaPrenatalCare(new Date(cursorFtoK.getLong(cursorFtoK.getColumnIndex(Zpo01DBConstants.seaPrenatalCare))));
        studyEntrySectionFtoK.setSeaMutiv(cursorFtoK.getString(cursorFtoK.getColumnIndex(Zpo01DBConstants.seaMutiv)));
        studyEntrySectionFtoK.setSeaIron(cursorFtoK.getString(cursorFtoK.getColumnIndex(Zpo01DBConstants.seaIron)));
        studyEntrySectionFtoK.setSeaOften(cursorFtoK.getString(cursorFtoK.getColumnIndex(Zpo01DBConstants.seaOften)));
        studyEntrySectionFtoK.setSeaIdCompleting(cursorFtoK.getString(cursorFtoK.getColumnIndex(Zpo01DBConstants.seaIdCompleting)));
        if (cursorFtoK.getLong(cursorFtoK.getColumnIndex(Zpo01DBConstants.seaDateCompleted))>0) studyEntrySectionFtoK.setSeaDateCompleted(new Date(cursorFtoK.getLong(cursorFtoK.getColumnIndex(Zpo01DBConstants.seaDateCompleted))));
        studyEntrySectionFtoK.setSeaIdReviewer(cursorFtoK.getString(cursorFtoK.getColumnIndex(Zpo01DBConstants.seaIdReviewer)));
        if (cursorFtoK.getLong(cursorFtoK.getColumnIndex(Zpo01DBConstants.seaDateReviewed))>0) studyEntrySectionFtoK.setSeaDateReviewed(new Date(cursorFtoK.getLong(cursorFtoK.getColumnIndex(Zpo01DBConstants.seaDateReviewed))));
        studyEntrySectionFtoK.setSeaIdDataEntry(cursorFtoK.getString(cursorFtoK.getColumnIndex(Zpo01DBConstants.seaIdDataEntry)));
        if (cursorFtoK.getLong(cursorFtoK.getColumnIndex(Zpo01DBConstants.seaDateEntered))>0) studyEntrySectionFtoK.setSeaDateEntered(new Date(cursorFtoK.getLong(cursorFtoK.getColumnIndex(Zpo01DBConstants.seaDateEntered))));

        //Movil y Metadata
        if(cursorFtoK.getLong(cursorFtoK.getColumnIndex(MainDBConstants.recordDate))>0) studyEntrySectionFtoK.setRecordDate(new Date(cursorFtoK.getLong(cursorFtoK.getColumnIndex(MainDBConstants.recordDate))));
        studyEntrySectionFtoK.setRecordUser(cursorFtoK.getString(cursorFtoK.getColumnIndex(MainDBConstants.recordUser)));
        studyEntrySectionFtoK.setPasive(cursorFtoK.getString(cursorFtoK.getColumnIndex(MainDBConstants.pasive)).charAt(0));
        studyEntrySectionFtoK.setIdInstancia(cursorFtoK.getInt(cursorFtoK.getColumnIndex(MainDBConstants.ID_INSTANCIA)));
        studyEntrySectionFtoK.setInstancePath(cursorFtoK.getString(cursorFtoK.getColumnIndex(MainDBConstants.FILE_PATH)));
        studyEntrySectionFtoK.setEstado(cursorFtoK.getString(cursorFtoK.getColumnIndex(MainDBConstants.STATUS)));
        studyEntrySectionFtoK.setStart(cursorFtoK.getString(cursorFtoK.getColumnIndex(MainDBConstants.START)));
        studyEntrySectionFtoK.setEnd(cursorFtoK.getString(cursorFtoK.getColumnIndex(MainDBConstants.END)));
        studyEntrySectionFtoK.setSimserial(cursorFtoK.getString(cursorFtoK.getColumnIndex(MainDBConstants.SIM_SERIAL)));
        studyEntrySectionFtoK.setPhonenumber(cursorFtoK.getString(cursorFtoK.getColumnIndex(MainDBConstants.PHONE_NUMBER)));
        studyEntrySectionFtoK.setDeviceid(cursorFtoK.getString(cursorFtoK.getColumnIndex(MainDBConstants.DEVICE_ID)));
        if(cursorFtoK.getLong(cursorFtoK.getColumnIndex(MainDBConstants.TODAY))>0) studyEntrySectionFtoK.setToday(new Date(cursorFtoK.getLong(cursorFtoK.getColumnIndex(MainDBConstants.TODAY))));

        return studyEntrySectionFtoK;
    }
}
