package ni.org.ics.zpo.appmovil.helpers;

import android.content.ContentValues;
import android.database.Cursor;
import ni.org.ics.zpo.domain.Zpo04ExtendedSectionAtoD;
import ni.org.ics.zpo.domain.Zpo04ExtendedSectionE;
import ni.org.ics.zpo.domain.Zpo04ExtendedSectionF;
import ni.org.ics.zpo.appmovil.utils.MainDBConstants;
import ni.org.ics.zpo.appmovil.utils.Zpo04DBConstants;

import java.util.Date;

/**
 * Created by FIRSTICT on 10/24/2016.
 * V1.0
 */
public class Zpo04ExtendedHelper {

    /*********************************************************
           PARA OBJETO Zpo04ExtendedSectionAtoD
     *********************************************************/
    public static ContentValues crearZpo04ExtendedSectionAtoD(Zpo04ExtendedSectionAtoD trimesterVisitSectionAtoD){
        ContentValues cv = new ContentValues();

        cv.put(Zpo04DBConstants.recordId, trimesterVisitSectionAtoD.getRecordId());
        cv.put(Zpo04DBConstants.eventName, trimesterVisitSectionAtoD.getEventName());
        if (trimesterVisitSectionAtoD.getTriDov()!=null) cv.put(Zpo04DBConstants.triDov, trimesterVisitSectionAtoD.getTriDov().getTime());
        cv.put(Zpo04DBConstants.triPrimJobInd, trimesterVisitSectionAtoD.getTriPrimJobInd());
        cv.put(Zpo04DBConstants.triPrimJobTitle, trimesterVisitSectionAtoD.getTriHusbJobTitle());
        cv.put(Zpo04DBConstants.triPrimJobTitleRef, trimesterVisitSectionAtoD.getTriHusbJobTitleRef());
        cv.put(Zpo04DBConstants.triPrimJobDat, trimesterVisitSectionAtoD.getTriPrimJobDat());
        cv.put(Zpo04DBConstants.triPrimJobYear, trimesterVisitSectionAtoD.getTriPrimJobYear());
        cv.put(Zpo04DBConstants.triPrimJobHours, trimesterVisitSectionAtoD.getTriPrimJobHours());
        cv.put(Zpo04DBConstants.triPrimJobHoursRef, trimesterVisitSectionAtoD.getTriPrimJobHoursRef());
        cv.put(Zpo04DBConstants.triPrimJobSetting, trimesterVisitSectionAtoD.getTriPrimJobSetting());
        cv.put(Zpo04DBConstants.triPrimJobSetRef, trimesterVisitSectionAtoD.getTriPrimJobSetRef());
        cv.put(Zpo04DBConstants.triPrimJobSetSpecify, trimesterVisitSectionAtoD.getTriPrimJobSetSpecify());
        cv.put(Zpo04DBConstants.triHusbJobInd, trimesterVisitSectionAtoD.getTriHusbJobInd());
        cv.put(Zpo04DBConstants.triHusbJobTitle, trimesterVisitSectionAtoD.getTriHusbJobTitle());
        cv.put(Zpo04DBConstants.triHusbJobTitleRef, trimesterVisitSectionAtoD.getTriHusbJobTitleRef());
        cv.put(Zpo04DBConstants.triHusbJobSet, trimesterVisitSectionAtoD.getTriHusbJobSet());
        cv.put(Zpo04DBConstants.triHusbJobSetRef, trimesterVisitSectionAtoD.getTriHusbJobSetRef());
        cv.put(Zpo04DBConstants.triHusbJobSetSpecify, trimesterVisitSectionAtoD.getTriHusbJobSetSpecify());
        cv.put(Zpo04DBConstants.triHouseSitInd, trimesterVisitSectionAtoD.getTriHouseSitInd());
        cv.put(Zpo04DBConstants.triCity, trimesterVisitSectionAtoD.getTriCity());
        cv.put(Zpo04DBConstants.triState, trimesterVisitSectionAtoD.getTriState());
        cv.put(Zpo04DBConstants.triCountry, trimesterVisitSectionAtoD.getTriCountry());
        cv.put(Zpo04DBConstants.triResidRef, trimesterVisitSectionAtoD.getTriResidRef());
        cv.put(Zpo04DBConstants.triCurrResidDur, trimesterVisitSectionAtoD.getTriCurrResidDur());
        cv.put(Zpo04DBConstants.triCurrResidDurRef, trimesterVisitSectionAtoD.getTriCurrResidDurRef());
        cv.put(Zpo04DBConstants.triNbhoodTyp, trimesterVisitSectionAtoD.getTriNbhoodTyp());
        cv.put(Zpo04DBConstants.triResidTyp, trimesterVisitSectionAtoD.getTriResidTyp());
        cv.put(Zpo04DBConstants.triResidTypSpecify, trimesterVisitSectionAtoD.getTriResidTypSpecify());
        cv.put(Zpo04DBConstants.triFloorMat, trimesterVisitSectionAtoD.getTriFloorMat());
        cv.put(Zpo04DBConstants.triFloorMatSpecify, trimesterVisitSectionAtoD.getTriFloorMatSpecify());
        cv.put(Zpo04DBConstants.triWallMat, trimesterVisitSectionAtoD.getTriWallMat());
        cv.put(Zpo04DBConstants.triWallMatSpecify, trimesterVisitSectionAtoD.getTriWallMatSpecify());
        cv.put(Zpo04DBConstants.triRoofMat, trimesterVisitSectionAtoD.getTriRoofMat());
        cv.put(Zpo04DBConstants.triRoofMatSpecify, trimesterVisitSectionAtoD.getTriRoofMatSpecify());
        cv.put(Zpo04DBConstants.triTrashDispos, trimesterVisitSectionAtoD.getTriTrashDispos());
        cv.put(Zpo04DBConstants.triTrashDisposSpecify, trimesterVisitSectionAtoD.getTriTrashDisposSpecify());
        cv.put(Zpo04DBConstants.triNumTotalRooms, trimesterVisitSectionAtoD.getTriNumTotalRooms());
        cv.put(Zpo04DBConstants.triNumSleepRooms, trimesterVisitSectionAtoD.getTriNumSleepRooms());
        cv.put(Zpo04DBConstants.triNumPeople, trimesterVisitSectionAtoD.getTriNumPeople());
        cv.put(Zpo04DBConstants.triScreensInd, trimesterVisitSectionAtoD.getTriScreensInd());
        cv.put(Zpo04DBConstants.triHouseAmenities, trimesterVisitSectionAtoD.getTriHouseAmenities());
        cv.put(Zpo04DBConstants.triTransAccess, trimesterVisitSectionAtoD.getTriTransAccess());
        cv.put(Zpo04DBConstants.triPrimWaterSrc, trimesterVisitSectionAtoD.getTriPrimWaterSrc());
        cv.put(Zpo04DBConstants.triWaterContainInd, trimesterVisitSectionAtoD.getTriWaterContainInd());
        cv.put(Zpo04DBConstants.triWaterContainTyp, trimesterVisitSectionAtoD.getTriWaterContainTyp());
        cv.put(Zpo04DBConstants.triWaterConSpecify, trimesterVisitSectionAtoD.getTriWaterConSpecify());
        cv.put(Zpo04DBConstants.triWaterTreatHome, trimesterVisitSectionAtoD.getTriWaterTreatHome());
        cv.put(Zpo04DBConstants.triWaterTreatFreq, trimesterVisitSectionAtoD.getTriWaterTreatFreq());
        cv.put(Zpo04DBConstants.triToiletTyp, trimesterVisitSectionAtoD.getTriToiletTyp());
        cv.put(Zpo04DBConstants.triToiletTypSpecify, trimesterVisitSectionAtoD.getTriToiletTypSpecify());
        cv.put(Zpo04DBConstants.triOpSewageInd, trimesterVisitSectionAtoD.getTriOpSewageInd());
        cv.put(Zpo04DBConstants.triAnimalsInd, trimesterVisitSectionAtoD.getTriAnimalsInd());
        cv.put(Zpo04DBConstants.triAnimalTyp, trimesterVisitSectionAtoD.getTriAnimalTyp());
        cv.put(Zpo04DBConstants.triAnimalSpecify, trimesterVisitSectionAtoD.getTriAnimalSpecify());
        cv.put(Zpo04DBConstants.triNumOtherAnimal, trimesterVisitSectionAtoD.getTriNumOtherAnimal());
        cv.put(Zpo04DBConstants.triNumCattle, trimesterVisitSectionAtoD.getTriNumCattle());
        cv.put(Zpo04DBConstants.triNumPig, trimesterVisitSectionAtoD.getTriNumPig());
        cv.put(Zpo04DBConstants.triNumFowl, trimesterVisitSectionAtoD.getTriNumFowl());
        cv.put(Zpo04DBConstants.triNumGoatsSheep, trimesterVisitSectionAtoD.getTriNumGoatsSheep());
        cv.put(Zpo04DBConstants.triSmokeInd, trimesterVisitSectionAtoD.getTriSmokeInd());
        cv.put(Zpo04DBConstants.triSmokeEverInd, trimesterVisitSectionAtoD.getTriSmokeEverInd());
        cv.put(Zpo04DBConstants.triSmokeCigPrevInd, trimesterVisitSectionAtoD.getTriSmokeCigPrevInd());
        cv.put(Zpo04DBConstants.triYearsSmoked, trimesterVisitSectionAtoD.getTriYearsSmoked());
        cv.put(Zpo04DBConstants.triYearsSmokedRef, trimesterVisitSectionAtoD.getTriYearsSmokedRef());
        cv.put(Zpo04DBConstants.triNumCigDay, trimesterVisitSectionAtoD.getTriNumCigDay());
        cv.put(Zpo04DBConstants.triNumCigRef, trimesterVisitSectionAtoD.getTriNumCigRef());
        cv.put(Zpo04DBConstants.triLastCig, trimesterVisitSectionAtoD.getTriLastCig());
        cv.put(Zpo04DBConstants.triHouseSmokeInd, trimesterVisitSectionAtoD.getTriHouseSmokeInd());
        cv.put(Zpo04DBConstants.triNumHrsSmoke, trimesterVisitSectionAtoD.getTriNumHrsSmoke());
        cv.put(Zpo04DBConstants.triNumHrsSmokeRef, trimesterVisitSectionAtoD.getTriNumHrsSmokeRef());
        cv.put(Zpo04DBConstants.triLastDrink, trimesterVisitSectionAtoD.getTriLastDrink());
        cv.put(Zpo04DBConstants.triDaysDrink, trimesterVisitSectionAtoD.getTriDaysDrink());
        cv.put(Zpo04DBConstants.triNumDrinks, trimesterVisitSectionAtoD.getTriNumDrinks());
        cv.put(Zpo04DBConstants.triMarijuanaInd, trimesterVisitSectionAtoD.getTriMarijuanaInd());
        cv.put(Zpo04DBConstants.triOtherDrugsInd, trimesterVisitSectionAtoD.getTriOtherDrugsInd());
        cv.put(Zpo04DBConstants.triOtherDrugs1, trimesterVisitSectionAtoD.getTriOtherDrugs1());
        cv.put(Zpo04DBConstants.triOtherDrugs2, trimesterVisitSectionAtoD.getTriOtherDrugs2());
        cv.put(Zpo04DBConstants.triOtherDrugs3, trimesterVisitSectionAtoD.getTriOtherDrugs3());
        cv.put(Zpo04DBConstants.triOtherDrugs4, trimesterVisitSectionAtoD.getTriOtherDrugs4());

        if (trimesterVisitSectionAtoD.getRecordDate() != null) cv.put(MainDBConstants.recordDate, trimesterVisitSectionAtoD.getRecordDate().getTime());
        cv.put(MainDBConstants.recordUser, trimesterVisitSectionAtoD.getRecordUser());
        cv.put(MainDBConstants.pasive, String.valueOf(trimesterVisitSectionAtoD.getPasive()));
        cv.put(MainDBConstants.ID_INSTANCIA, trimesterVisitSectionAtoD.getIdInstancia());
        cv.put(MainDBConstants.FILE_PATH, trimesterVisitSectionAtoD.getInstancePath());
        cv.put(MainDBConstants.STATUS, trimesterVisitSectionAtoD.getEstado());
        cv.put(MainDBConstants.START, trimesterVisitSectionAtoD.getStart());
        cv.put(MainDBConstants.END, trimesterVisitSectionAtoD.getEnd());
        cv.put(MainDBConstants.DEVICE_ID, trimesterVisitSectionAtoD.getDeviceid());
        cv.put(MainDBConstants.SIM_SERIAL, trimesterVisitSectionAtoD.getSimserial());
        cv.put(MainDBConstants.PHONE_NUMBER, trimesterVisitSectionAtoD.getPhonenumber());
        if (trimesterVisitSectionAtoD.getToday() != null) cv.put(MainDBConstants.TODAY, trimesterVisitSectionAtoD.getToday().getTime());

        return cv;
    }

    public static Zpo04ExtendedSectionAtoD crearZpo04ExtendedSectionAtoD(Cursor cursorAD){
        Zpo04ExtendedSectionAtoD trimesterVisitSectionAtoD = new Zpo04ExtendedSectionAtoD();

        trimesterVisitSectionAtoD.setRecordId(cursorAD.getString(cursorAD.getColumnIndex(Zpo04DBConstants.recordId)));
        trimesterVisitSectionAtoD.setEventName(cursorAD.getString(cursorAD.getColumnIndex(Zpo04DBConstants.eventName)));
        if (cursorAD.getLong(cursorAD.getColumnIndex(Zpo04DBConstants.triDov))>0) trimesterVisitSectionAtoD.setTriDov(new Date(cursorAD.getLong(cursorAD.getColumnIndex(Zpo04DBConstants.triDov))));
        trimesterVisitSectionAtoD.setTriPrimJobInd(cursorAD.getString(cursorAD.getColumnIndex(Zpo04DBConstants.triPrimJobInd)));
        trimesterVisitSectionAtoD.setTriPrimJobTitle(cursorAD.getString(cursorAD.getColumnIndex(Zpo04DBConstants.triPrimJobTitle)));
        trimesterVisitSectionAtoD.setTriPrimJobTitleRef(cursorAD.getString(cursorAD.getColumnIndex(Zpo04DBConstants.triPrimJobTitleRef)));
        trimesterVisitSectionAtoD.setTriPrimJobDat(cursorAD.getString(cursorAD.getColumnIndex(Zpo04DBConstants.triPrimJobDat)));
        trimesterVisitSectionAtoD.setTriPrimJobYear(cursorAD.getString(cursorAD.getColumnIndex(Zpo04DBConstants.triPrimJobYear)));
        trimesterVisitSectionAtoD.setTriPrimJobHours(cursorAD.getString(cursorAD.getColumnIndex(Zpo04DBConstants.triPrimJobHours)));
        trimesterVisitSectionAtoD.setTriPrimJobHoursRef(cursorAD.getString(cursorAD.getColumnIndex(Zpo04DBConstants.triPrimJobHoursRef)));
        trimesterVisitSectionAtoD.setTriPrimJobSetting(cursorAD.getString(cursorAD.getColumnIndex(Zpo04DBConstants.triPrimJobSetting)));
        trimesterVisitSectionAtoD.setTriPrimJobSetRef(cursorAD.getString(cursorAD.getColumnIndex(Zpo04DBConstants.triPrimJobSetRef)));
        trimesterVisitSectionAtoD.setTriPrimJobSetSpecify(cursorAD.getString(cursorAD.getColumnIndex(Zpo04DBConstants.triPrimJobSetSpecify)));
        trimesterVisitSectionAtoD.setTriHusbJobInd(cursorAD.getString(cursorAD.getColumnIndex(Zpo04DBConstants.triHusbJobInd)));
        trimesterVisitSectionAtoD.setTriHusbJobTitle(cursorAD.getString(cursorAD.getColumnIndex(Zpo04DBConstants.triHusbJobTitle)));
        trimesterVisitSectionAtoD.setTriHusbJobTitleRef(cursorAD.getString(cursorAD.getColumnIndex(Zpo04DBConstants.triHusbJobTitleRef)));
        trimesterVisitSectionAtoD.setTriHusbJobSet(cursorAD.getString(cursorAD.getColumnIndex(Zpo04DBConstants.triHusbJobSet)));
        trimesterVisitSectionAtoD.setTriHusbJobSetRef(cursorAD.getString(cursorAD.getColumnIndex(Zpo04DBConstants.triHusbJobSetRef)));
        trimesterVisitSectionAtoD.setTriHusbJobSetSpecify(cursorAD.getString(cursorAD.getColumnIndex(Zpo04DBConstants.triHusbJobSetSpecify)));
        trimesterVisitSectionAtoD.setTriHouseSitInd(cursorAD.getString(cursorAD.getColumnIndex(Zpo04DBConstants.triHouseSitInd)));
        trimesterVisitSectionAtoD.setTriCity(cursorAD.getString(cursorAD.getColumnIndex(Zpo04DBConstants.triCity)));
        trimesterVisitSectionAtoD.setTriState(cursorAD.getString(cursorAD.getColumnIndex(Zpo04DBConstants.triState)));
        trimesterVisitSectionAtoD.setTriCountry(cursorAD.getString(cursorAD.getColumnIndex(Zpo04DBConstants.triCountry)));
        trimesterVisitSectionAtoD.setTriResidRef(cursorAD.getString(cursorAD.getColumnIndex(Zpo04DBConstants.triResidRef)));
        trimesterVisitSectionAtoD.setTriCurrResidDur(cursorAD.getString(cursorAD.getColumnIndex(Zpo04DBConstants.triCurrResidDur)));
        trimesterVisitSectionAtoD.setTriCurrResidDurRef(cursorAD.getString(cursorAD.getColumnIndex(Zpo04DBConstants.triCurrResidDurRef)));
        trimesterVisitSectionAtoD.setTriNbhoodTyp(cursorAD.getString(cursorAD.getColumnIndex(Zpo04DBConstants.triNbhoodTyp)));
        trimesterVisitSectionAtoD.setTriResidTyp(cursorAD.getString(cursorAD.getColumnIndex(Zpo04DBConstants.triResidTyp)));
        trimesterVisitSectionAtoD.setTriResidTypSpecify(cursorAD.getString(cursorAD.getColumnIndex(Zpo04DBConstants.triResidTypSpecify)));
        trimesterVisitSectionAtoD.setTriFloorMat(cursorAD.getString(cursorAD.getColumnIndex(Zpo04DBConstants.triFloorMat)));
        trimesterVisitSectionAtoD.setTriFloorMatSpecify(cursorAD.getString(cursorAD.getColumnIndex(Zpo04DBConstants.triFloorMatSpecify)));
        trimesterVisitSectionAtoD.setTriWallMat(cursorAD.getString(cursorAD.getColumnIndex(Zpo04DBConstants.triWallMat)));
        trimesterVisitSectionAtoD.setTriWallMatSpecify(cursorAD.getString(cursorAD.getColumnIndex(Zpo04DBConstants.triWallMatSpecify)));
        trimesterVisitSectionAtoD.setTriRoofMat(cursorAD.getString(cursorAD.getColumnIndex(Zpo04DBConstants.triRoofMat)));
        trimesterVisitSectionAtoD.setTriRoofMatSpecify(cursorAD.getString(cursorAD.getColumnIndex(Zpo04DBConstants.triRoofMatSpecify)));
        trimesterVisitSectionAtoD.setTriTrashDispos(cursorAD.getString(cursorAD.getColumnIndex(Zpo04DBConstants.triTrashDispos)));
        trimesterVisitSectionAtoD.setTriTrashDisposSpecify(cursorAD.getString(cursorAD.getColumnIndex(Zpo04DBConstants.triTrashDisposSpecify)));
        if (cursorAD.getInt(cursorAD.getColumnIndex(Zpo04DBConstants.triNumTotalRooms))>0) trimesterVisitSectionAtoD.setTriNumTotalRooms(cursorAD.getInt(cursorAD.getColumnIndex(Zpo04DBConstants.triNumTotalRooms)));
        if (cursorAD.getInt(cursorAD.getColumnIndex(Zpo04DBConstants.triNumSleepRooms))>0) trimesterVisitSectionAtoD.setTriNumSleepRooms(cursorAD.getInt(cursorAD.getColumnIndex(Zpo04DBConstants.triNumSleepRooms)));
        if (cursorAD.getInt(cursorAD.getColumnIndex(Zpo04DBConstants.triNumPeople))>0) trimesterVisitSectionAtoD.setTriNumPeople(cursorAD.getInt(cursorAD.getColumnIndex(Zpo04DBConstants.triNumPeople)));
        trimesterVisitSectionAtoD.setTriScreensInd(cursorAD.getString(cursorAD.getColumnIndex(Zpo04DBConstants.triScreensInd)));
        trimesterVisitSectionAtoD.setTriHouseAmenities(cursorAD.getString(cursorAD.getColumnIndex(Zpo04DBConstants.triHouseAmenities)));
        trimesterVisitSectionAtoD.setTriTransAccess(cursorAD.getString(cursorAD.getColumnIndex(Zpo04DBConstants.triTransAccess)));
        trimesterVisitSectionAtoD.setTriPrimWaterSrc(cursorAD.getString(cursorAD.getColumnIndex(Zpo04DBConstants.triPrimWaterSrc)));
        trimesterVisitSectionAtoD.setTriWaterContainInd(cursorAD.getString(cursorAD.getColumnIndex(Zpo04DBConstants.triWaterContainInd)));
        trimesterVisitSectionAtoD.setTriWaterContainTyp(cursorAD.getString(cursorAD.getColumnIndex(Zpo04DBConstants.triWaterContainTyp)));
        trimesterVisitSectionAtoD.setTriWaterConSpecify(cursorAD.getString(cursorAD.getColumnIndex(Zpo04DBConstants.triWaterConSpecify)));
        trimesterVisitSectionAtoD.setTriWaterTreatHome(cursorAD.getString(cursorAD.getColumnIndex(Zpo04DBConstants.triWaterTreatHome)));
        trimesterVisitSectionAtoD.setTriWaterTreatFreq(cursorAD.getString(cursorAD.getColumnIndex(Zpo04DBConstants.triWaterTreatFreq)));
        trimesterVisitSectionAtoD.setTriToiletTyp(cursorAD.getString(cursorAD.getColumnIndex(Zpo04DBConstants.triToiletTyp)));
        trimesterVisitSectionAtoD.setTriToiletTypSpecify(cursorAD.getString(cursorAD.getColumnIndex(Zpo04DBConstants.triToiletTypSpecify)));
        trimesterVisitSectionAtoD.setTriOpSewageInd(cursorAD.getString(cursorAD.getColumnIndex(Zpo04DBConstants.triOpSewageInd)));
        trimesterVisitSectionAtoD.setTriAnimalsInd(cursorAD.getString(cursorAD.getColumnIndex(Zpo04DBConstants.triAnimalsInd)));
        trimesterVisitSectionAtoD.setTriAnimalTyp(cursorAD.getString(cursorAD.getColumnIndex(Zpo04DBConstants.triAnimalTyp)));
        trimesterVisitSectionAtoD.setTriAnimalSpecify(cursorAD.getString(cursorAD.getColumnIndex(Zpo04DBConstants.triAnimalSpecify)));
        if(cursorAD.getInt(cursorAD.getColumnIndex(Zpo04DBConstants.triNumOtherAnimal))>0) trimesterVisitSectionAtoD.setTriNumOtherAnimal(cursorAD.getInt(cursorAD.getColumnIndex(Zpo04DBConstants.triNumOtherAnimal)));
        if(cursorAD.getInt(cursorAD.getColumnIndex(Zpo04DBConstants.triNumCattle))>0) trimesterVisitSectionAtoD.setTriNumCattle(cursorAD.getInt(cursorAD.getColumnIndex(Zpo04DBConstants.triNumCattle)));
        if(cursorAD.getInt(cursorAD.getColumnIndex(Zpo04DBConstants.triNumPig))>0) trimesterVisitSectionAtoD.setTriNumPig(cursorAD.getInt(cursorAD.getColumnIndex(Zpo04DBConstants.triNumPig)));
        if(cursorAD.getInt(cursorAD.getColumnIndex(Zpo04DBConstants.triNumFowl))>0) trimesterVisitSectionAtoD.setTriNumFowl(cursorAD.getInt(cursorAD.getColumnIndex(Zpo04DBConstants.triNumFowl)));
        if(cursorAD.getInt(cursorAD.getColumnIndex(Zpo04DBConstants.triNumGoatsSheep))>0) trimesterVisitSectionAtoD.setTriNumGoatsSheep(cursorAD.getInt(cursorAD.getColumnIndex(Zpo04DBConstants.triNumGoatsSheep)));
        trimesterVisitSectionAtoD.setTriSmokeInd(cursorAD.getString(cursorAD.getColumnIndex(Zpo04DBConstants.triSmokeInd)));
        trimesterVisitSectionAtoD.setTriSmokeEverInd(cursorAD.getString(cursorAD.getColumnIndex(Zpo04DBConstants.triSmokeEverInd)));
        trimesterVisitSectionAtoD.setTriSmokeCigPrevInd(cursorAD.getString(cursorAD.getColumnIndex(Zpo04DBConstants.triSmokeCigPrevInd)));
        trimesterVisitSectionAtoD.setTriYearsSmoked(cursorAD.getString(cursorAD.getColumnIndex(Zpo04DBConstants.triYearsSmoked)));
        trimesterVisitSectionAtoD.setTriYearsSmokedRef(cursorAD.getString(cursorAD.getColumnIndex(Zpo04DBConstants.triYearsSmokedRef)));
        if (cursorAD.getFloat(cursorAD.getColumnIndex(Zpo04DBConstants.triNumCigDay))>0) trimesterVisitSectionAtoD.setTriNumCigDay(cursorAD.getFloat(cursorAD.getColumnIndex(Zpo04DBConstants.triNumCigDay)));
        trimesterVisitSectionAtoD.setTriNumCigRef(cursorAD.getString(cursorAD.getColumnIndex(Zpo04DBConstants.triNumCigRef)));
        trimesterVisitSectionAtoD.setTriLastCig(cursorAD.getString(cursorAD.getColumnIndex(Zpo04DBConstants.triLastCig)));
        trimesterVisitSectionAtoD.setTriHouseSmokeInd(cursorAD.getString(cursorAD.getColumnIndex(Zpo04DBConstants.triHouseSmokeInd)));
        trimesterVisitSectionAtoD.setTriNumHrsSmoke(cursorAD.getString(cursorAD.getColumnIndex(Zpo04DBConstants.triNumHrsSmoke)));
        trimesterVisitSectionAtoD.setTriNumHrsSmokeRef(cursorAD.getString(cursorAD.getColumnIndex(Zpo04DBConstants.triNumHrsSmokeRef)));
        trimesterVisitSectionAtoD.setTriLastDrink(cursorAD.getString(cursorAD.getColumnIndex(Zpo04DBConstants.triLastDrink)));
        trimesterVisitSectionAtoD.setTriDaysDrink(cursorAD.getString(cursorAD.getColumnIndex(Zpo04DBConstants.triDaysDrink)));
        trimesterVisitSectionAtoD.setTriNumDrinks(cursorAD.getString(cursorAD.getColumnIndex(Zpo04DBConstants.triNumDrinks)));
        trimesterVisitSectionAtoD.setTriMarijuanaInd(cursorAD.getString(cursorAD.getColumnIndex(Zpo04DBConstants.triMarijuanaInd)));
        trimesterVisitSectionAtoD.setTriOtherDrugsInd(cursorAD.getString(cursorAD.getColumnIndex(Zpo04DBConstants.triOtherDrugsInd)));
        trimesterVisitSectionAtoD.setTriOtherDrugs1(cursorAD.getString(cursorAD.getColumnIndex(Zpo04DBConstants.triOtherDrugs1)));
        trimesterVisitSectionAtoD.setTriOtherDrugs2(cursorAD.getString(cursorAD.getColumnIndex(Zpo04DBConstants.triOtherDrugs2)));
        trimesterVisitSectionAtoD.setTriOtherDrugs3(cursorAD.getString(cursorAD.getColumnIndex(Zpo04DBConstants.triOtherDrugs3)));
        trimesterVisitSectionAtoD.setTriOtherDrugs4(cursorAD.getString(cursorAD.getColumnIndex(Zpo04DBConstants.triOtherDrugs4)));

        //Movil y Metadata
        if(cursorAD.getLong(cursorAD.getColumnIndex(MainDBConstants.recordDate))>0) trimesterVisitSectionAtoD.setRecordDate(new Date(cursorAD.getLong(cursorAD.getColumnIndex(MainDBConstants.recordDate))));
        trimesterVisitSectionAtoD.setRecordUser(cursorAD.getString(cursorAD.getColumnIndex(MainDBConstants.recordUser)));
        trimesterVisitSectionAtoD.setPasive(cursorAD.getString(cursorAD.getColumnIndex(MainDBConstants.pasive)).charAt(0));
        trimesterVisitSectionAtoD.setIdInstancia(cursorAD.getInt(cursorAD.getColumnIndex(MainDBConstants.ID_INSTANCIA)));
        trimesterVisitSectionAtoD.setInstancePath(cursorAD.getString(cursorAD.getColumnIndex(MainDBConstants.FILE_PATH)));
        trimesterVisitSectionAtoD.setEstado(cursorAD.getString(cursorAD.getColumnIndex(MainDBConstants.STATUS)));
        trimesterVisitSectionAtoD.setStart(cursorAD.getString(cursorAD.getColumnIndex(MainDBConstants.START)));
        trimesterVisitSectionAtoD.setEnd(cursorAD.getString(cursorAD.getColumnIndex(MainDBConstants.END)));
        trimesterVisitSectionAtoD.setSimserial(cursorAD.getString(cursorAD.getColumnIndex(MainDBConstants.SIM_SERIAL)));
        trimesterVisitSectionAtoD.setPhonenumber(cursorAD.getString(cursorAD.getColumnIndex(MainDBConstants.PHONE_NUMBER)));
        trimesterVisitSectionAtoD.setDeviceid(cursorAD.getString(cursorAD.getColumnIndex(MainDBConstants.DEVICE_ID)));
        if(cursorAD.getLong(cursorAD.getColumnIndex(MainDBConstants.TODAY))>0) trimesterVisitSectionAtoD.setToday(new Date(cursorAD.getLong(cursorAD.getColumnIndex(MainDBConstants.TODAY))));

        return trimesterVisitSectionAtoD;
    }

    /*********************************************************
     PARA OBJETO Zpo04ExtendedSectionE
     *********************************************************/
    public static ContentValues crearZpo04ExtendedSectionE(Zpo04ExtendedSectionE trimesterVisitSectionE){
        ContentValues cv = new ContentValues();
        cv.put(Zpo04DBConstants.recordId, trimesterVisitSectionE.getRecordId());
        cv.put(Zpo04DBConstants.eventName, trimesterVisitSectionE.getEventName());
        cv.put(Zpo04DBConstants.tri24HrsDeodorant, trimesterVisitSectionE.getTri24HrsDeodorant());
        cv.put(Zpo04DBConstants.triBrandDeodorant, trimesterVisitSectionE.getTriBrandDeodorant());
        cv.put(Zpo04DBConstants.triFragFreeDeodorant, trimesterVisitSectionE.getTriFragFreeDeodorant());
        cv.put(Zpo04DBConstants.tri24HrsHairGel, trimesterVisitSectionE.getTri24HrsHairGel());
        cv.put(Zpo04DBConstants.triBrandHairGel, trimesterVisitSectionE.getTriBrandHairGel());
        cv.put(Zpo04DBConstants.triFragFreeHairGel, trimesterVisitSectionE.getTriFragFreeHairGel());
        cv.put(Zpo04DBConstants.tri24HrsConditioner, trimesterVisitSectionE.getTri24HrsConditioner());
        cv.put(Zpo04DBConstants.triBrandConditioner, trimesterVisitSectionE.getTriBrandConditioner());
        cv.put(Zpo04DBConstants.triFragFreeConditioner, trimesterVisitSectionE.getTriFragFreeConditioner());
        cv.put(Zpo04DBConstants.tri24HrsShampoo, trimesterVisitSectionE.getTri24HrsShampoo());
        cv.put(Zpo04DBConstants.triBrandShampoo, trimesterVisitSectionE.getTriBrandShampoo());
        cv.put(Zpo04DBConstants.triFragFreeShampoo, trimesterVisitSectionE.getTriFragFreeShampoo());
        cv.put(Zpo04DBConstants.tri24HrsOtherHair, trimesterVisitSectionE.getTri24HrsOtherHair());
        cv.put(Zpo04DBConstants.triBrandOtherHair, trimesterVisitSectionE.getTriBrandOtherHair());
        cv.put(Zpo04DBConstants.triFragFreeOtherHair, trimesterVisitSectionE.getTriFragFreeOtherHair());
        cv.put(Zpo04DBConstants.tri24HrsPerfume, trimesterVisitSectionE.getTri24HrsPerfume());
        cv.put(Zpo04DBConstants.triBrandPerfume, trimesterVisitSectionE.getTriBrandPerfume());
        cv.put(Zpo04DBConstants.triFragFreePerfume, trimesterVisitSectionE.getTriFragFreePerfume());
        cv.put(Zpo04DBConstants.tri24HrsBarSoap, trimesterVisitSectionE.getTri24HrsBarSoap());
        cv.put(Zpo04DBConstants.triBrandBarSoap, trimesterVisitSectionE.getTriBrandBarSoap());
        cv.put(Zpo04DBConstants.triFragFreeBarSoap, trimesterVisitSectionE.getTriFragFreeBarSoap());
        cv.put(Zpo04DBConstants.tri24HrsLiqSoap, trimesterVisitSectionE.getTri24HrsLiqSoap());
        cv.put(Zpo04DBConstants.triBrandLiqSoap, trimesterVisitSectionE.getTriBrandLiqSoap());
        cv.put(Zpo04DBConstants.triFragFreeLiqSoap, trimesterVisitSectionE.getTriFragFreeLiqSoap());
        cv.put(Zpo04DBConstants.tri24HrsLotion, trimesterVisitSectionE.getTri24HrsLotion());
        cv.put(Zpo04DBConstants.triBrandLotion, trimesterVisitSectionE.getTriBrandLotion());
        cv.put(Zpo04DBConstants.triFragFreeLotion, trimesterVisitSectionE.getTriFragFreeLotion());
        cv.put(Zpo04DBConstants.tri24HrsShavCream, trimesterVisitSectionE.getTri24HrsShavCream());
        cv.put(Zpo04DBConstants.triBrandShavCream, trimesterVisitSectionE.getTriBrandShavCream());
        cv.put(Zpo04DBConstants.triFragFreeShavCream, trimesterVisitSectionE.getTriFragFreeShavCream());
        cv.put(Zpo04DBConstants.tri24HrsColorCos, trimesterVisitSectionE.getTri24HrsColorCos());
        cv.put(Zpo04DBConstants.triBrandColorCos, trimesterVisitSectionE.getTriBrandColorCos());
        cv.put(Zpo04DBConstants.triFragFreeColorCos, trimesterVisitSectionE.getTriFragFreeColorCos());
        cv.put(Zpo04DBConstants.tri24HrsSunscreen, trimesterVisitSectionE.getTri24HrsSunscreen());
        cv.put(Zpo04DBConstants.triBrandSunscreen, trimesterVisitSectionE.getTriBrandSunscreen());
        cv.put(Zpo04DBConstants.triFragFreeSunscreen, trimesterVisitSectionE.getTriFragFreeSunscreen());
        cv.put(Zpo04DBConstants.tri24HrsNailPol, trimesterVisitSectionE.getTri24HrsNailPol());
        cv.put(Zpo04DBConstants.triBrandNailPol, trimesterVisitSectionE.getTriBrandNailPol());
        cv.put(Zpo04DBConstants.triFragFreeNailPol, trimesterVisitSectionE.getTriFragFreeNailPol());
        cv.put(Zpo04DBConstants.tri24HrsFurnPol, trimesterVisitSectionE.getTri24HrsFurnPol());
        cv.put(Zpo04DBConstants.triBrandFurnPol, trimesterVisitSectionE.getTriBrandFurnPol());
        cv.put(Zpo04DBConstants.triFragFreeFurnPol, trimesterVisitSectionE.getTriFragFreeFurnPol());
        cv.put(Zpo04DBConstants.tri24HrsCleaners, trimesterVisitSectionE.getTri24HrsCleaners());
        cv.put(Zpo04DBConstants.triBrandCleaners, trimesterVisitSectionE.getTriBrandCleaners());
        cv.put(Zpo04DBConstants.triFragFreeCleaners, trimesterVisitSectionE.getTriFragFreeCleaners());
        cv.put(Zpo04DBConstants.tri24HrsFloorWax, trimesterVisitSectionE.getTri24HrsFloorWax());
        cv.put(Zpo04DBConstants.triBrandFloorWax, trimesterVisitSectionE.getTriBrandFloorWax());
        cv.put(Zpo04DBConstants.triFragFreeFloorWax, trimesterVisitSectionE.getTriFragFreeFloorWax());
        cv.put(Zpo04DBConstants.tri24HrsSoftnr, trimesterVisitSectionE.getTri24HrsSoftnr());
        cv.put(Zpo04DBConstants.triBrandSoftnr, trimesterVisitSectionE.getTriBrandSoftnr());
        cv.put(Zpo04DBConstants.triFragFreeSoftnr, trimesterVisitSectionE.getTriFragFreeSoftnr());
        cv.put(Zpo04DBConstants.tri24HrsLaundDet, trimesterVisitSectionE.getTri24HrsLaundDet());
        cv.put(Zpo04DBConstants.triBrandLaundDet, trimesterVisitSectionE.getTriBrandLaundDet());
        cv.put(Zpo04DBConstants.triFragFreeLaundDet, trimesterVisitSectionE.getTriFragFreeLaundDet());
        cv.put(Zpo04DBConstants.tri24HrsLaundStrch, trimesterVisitSectionE.getTri24HrsLaundStrch());
        cv.put(Zpo04DBConstants.triBrandLaundStrch, trimesterVisitSectionE.getTriBrandLaundStrch());
        cv.put(Zpo04DBConstants.triFragFreeLaundStrch, trimesterVisitSectionE.getTriFragFreeLaundStrch());
        cv.put(Zpo04DBConstants.tri24HrsPaint, trimesterVisitSectionE.getTri24HrsPaint());
        cv.put(Zpo04DBConstants.triBrandPaint, trimesterVisitSectionE.getTriBrandPaint());
        cv.put(Zpo04DBConstants.triFragFreePaint, trimesterVisitSectionE.getTriFragFreePaint());
        cv.put(Zpo04DBConstants.tri24HrsSolvents, trimesterVisitSectionE.getTri24HrsSolvents());
        cv.put(Zpo04DBConstants.triBrandSolvents, trimesterVisitSectionE.getTriBrandSolvents());
        cv.put(Zpo04DBConstants.triFragFreeSolvents, trimesterVisitSectionE.getTriFragFreeSolvents());
        cv.put(Zpo04DBConstants.tri24HrsCarWax, trimesterVisitSectionE.getTri24HrsCarWax());
        cv.put(Zpo04DBConstants.triBrandCarWax, trimesterVisitSectionE.getTriBrandCarWax());
        cv.put(Zpo04DBConstants.triFragFreeCarWax, trimesterVisitSectionE.getTriFragFreeCarWax());
        cv.put(Zpo04DBConstants.tri24HrsPest, trimesterVisitSectionE.getTri24HrsPest());
        cv.put(Zpo04DBConstants.triBrandPest, trimesterVisitSectionE.getTriBrandPest());
        cv.put(Zpo04DBConstants.triFragFreePest, trimesterVisitSectionE.getTriFragFreePest());
        cv.put(Zpo04DBConstants.tri24HrsFleaTickPrev, trimesterVisitSectionE.getTri24HrsFleaTickPrev());
        cv.put(Zpo04DBConstants.triBrandFleaTickPrev, trimesterVisitSectionE.getTriFleaTickPrev());
        cv.put(Zpo04DBConstants.triFleaTickPrev, trimesterVisitSectionE.getTriFleaTickPrev());
        cv.put(Zpo04DBConstants.tri24HrsFleaTickSpry, trimesterVisitSectionE.getTri24HrsFleaTickSpry());
        cv.put(Zpo04DBConstants.triBrandFleaTickSpry, trimesterVisitSectionE.getTriBrandFleaTickSpry());
        cv.put(Zpo04DBConstants.triFleaTickSpry, trimesterVisitSectionE.getTriFleaTickSpry());
        cv.put(Zpo04DBConstants.tri24HrsCaritin, trimesterVisitSectionE.getTri24HrsCaritin());
        cv.put(Zpo04DBConstants.triBrandCaritin, trimesterVisitSectionE.getTriBrandCaritin());
        cv.put(Zpo04DBConstants.triFragFreeCaritin, trimesterVisitSectionE.getTriFragFreeCaritin());
        cv.put(Zpo04DBConstants.tri24HrsZyrtec, trimesterVisitSectionE.getTri24HrsZyrtec());
        cv.put(Zpo04DBConstants.triBrandZyrtec, trimesterVisitSectionE.getTriBrandZyrtec());
        cv.put(Zpo04DBConstants.triFragFreeZyrtec, trimesterVisitSectionE.getTriFragFreeZyrtec());
        cv.put(Zpo04DBConstants.tri24HrsVita, trimesterVisitSectionE.getTri24HrsVita());
        cv.put(Zpo04DBConstants.triBrandVita, trimesterVisitSectionE.getTriBrandVita());
        cv.put(Zpo04DBConstants.triFragFreeVita, trimesterVisitSectionE.getTriFragFreeVita());
        cv.put(Zpo04DBConstants.tri24HrsHerbal, trimesterVisitSectionE.getTri24HrsHerbal());
        cv.put(Zpo04DBConstants.triBrandHerbal, trimesterVisitSectionE.getTriBrandHerbal());
        cv.put(Zpo04DBConstants.triFragFreeHerbal, trimesterVisitSectionE.getTriFragFreeHerbal());
        cv.put(Zpo04DBConstants.tri24HrsCreatine, trimesterVisitSectionE.getTri24HrsCreatine());
        cv.put(Zpo04DBConstants.triBrandCreatine, trimesterVisitSectionE.getTriBrandCreatine());
        cv.put(Zpo04DBConstants.triFragFreeCreatine, trimesterVisitSectionE.getTriFragFreeCreatine());
        cv.put(Zpo04DBConstants.tri24HrsProtein, trimesterVisitSectionE.getTri24HrsProtein());
        cv.put(Zpo04DBConstants.triBrandProtein, trimesterVisitSectionE.getTriBrandProtein());
        cv.put(Zpo04DBConstants.triFragFreeProtein, trimesterVisitSectionE.getTriFragFreeProtein());
        cv.put(Zpo04DBConstants.tri24HrsDiuretic, trimesterVisitSectionE.getTri24HrsDiuretic());
        cv.put(Zpo04DBConstants.triBrandDiuretic, trimesterVisitSectionE.getTriBrandDiuretic());
        cv.put(Zpo04DBConstants.triFragFreeDiuretic, trimesterVisitSectionE.getTriFragFreeDiuretic());
        cv.put(Zpo04DBConstants.tri24HrsInsulin, trimesterVisitSectionE.getTri24HrsInsulin());
        cv.put(Zpo04DBConstants.triBrandInsulin, trimesterVisitSectionE.getTriBrandInsulin());
        cv.put(Zpo04DBConstants.triFragFreeInsulin, trimesterVisitSectionE.getTriFragFreeInsulin());
        cv.put(Zpo04DBConstants.tri24HrsMouthwsh, trimesterVisitSectionE.getTri24HrsMouthwsh());
        cv.put(Zpo04DBConstants.triBrandMouthwsh, trimesterVisitSectionE.getTriBrandMouthwsh());
        cv.put(Zpo04DBConstants.triFragFreeMouthwsh, trimesterVisitSectionE.getTriFragFreeMouthwsh());
        cv.put(Zpo04DBConstants.triFragFreeOverall, trimesterVisitSectionE.getTriFragFreeOverall());
        cv.put(Zpo04DBConstants.triSurgInd, trimesterVisitSectionE.getTriSurgInd());

        if (trimesterVisitSectionE.getRecordDate() != null) cv.put(MainDBConstants.recordDate, trimesterVisitSectionE.getRecordDate().getTime());
        cv.put(MainDBConstants.recordUser, trimesterVisitSectionE.getRecordUser());
        cv.put(MainDBConstants.pasive, String.valueOf(trimesterVisitSectionE.getPasive()));
        cv.put(MainDBConstants.ID_INSTANCIA, trimesterVisitSectionE.getIdInstancia());
        cv.put(MainDBConstants.FILE_PATH, trimesterVisitSectionE.getInstancePath());
        cv.put(MainDBConstants.STATUS, trimesterVisitSectionE.getEstado());
        cv.put(MainDBConstants.START, trimesterVisitSectionE.getStart());
        cv.put(MainDBConstants.END, trimesterVisitSectionE.getEnd());
        cv.put(MainDBConstants.DEVICE_ID, trimesterVisitSectionE.getDeviceid());
        cv.put(MainDBConstants.SIM_SERIAL, trimesterVisitSectionE.getSimserial());
        cv.put(MainDBConstants.PHONE_NUMBER, trimesterVisitSectionE.getPhonenumber());
        if (trimesterVisitSectionE.getToday() != null) cv.put(MainDBConstants.TODAY, trimesterVisitSectionE.getToday().getTime());

        return cv;
    }

    public static Zpo04ExtendedSectionE crearZpo04ExtendedSectionE(Cursor cursorE){
        Zpo04ExtendedSectionE trimesterVisitSectionE = new Zpo04ExtendedSectionE();

        trimesterVisitSectionE.setRecordId(cursorE.getString(cursorE.getColumnIndex(Zpo04DBConstants.recordId)));
        trimesterVisitSectionE.setEventName(cursorE.getString(cursorE.getColumnIndex(Zpo04DBConstants.eventName)));
        trimesterVisitSectionE.setTri24HrsDeodorant(cursorE.getString(cursorE.getColumnIndex(Zpo04DBConstants.tri24HrsDeodorant)));
        trimesterVisitSectionE.setTriBrandDeodorant(cursorE.getString(cursorE.getColumnIndex(Zpo04DBConstants.triBrandDeodorant)));
        trimesterVisitSectionE.setTriFragFreeDeodorant(cursorE.getString(cursorE.getColumnIndex(Zpo04DBConstants.triFragFreeDeodorant)));
        trimesterVisitSectionE.setTri24HrsHairGel(cursorE.getString(cursorE.getColumnIndex(Zpo04DBConstants.tri24HrsHairGel)));
        trimesterVisitSectionE.setTriBrandHairGel(cursorE.getString(cursorE.getColumnIndex(Zpo04DBConstants.triBrandHairGel)));
        trimesterVisitSectionE.setTriFragFreeHairGel(cursorE.getString(cursorE.getColumnIndex(Zpo04DBConstants.triFragFreeHairGel)));
        trimesterVisitSectionE.setTri24HrsConditioner(cursorE.getString(cursorE.getColumnIndex(Zpo04DBConstants.tri24HrsConditioner)));
        trimesterVisitSectionE.setTriBrandConditioner(cursorE.getString(cursorE.getColumnIndex(Zpo04DBConstants.triBrandConditioner)));
        trimesterVisitSectionE.setTriFragFreeConditioner(cursorE.getString(cursorE.getColumnIndex(Zpo04DBConstants.triFragFreeConditioner)));
        trimesterVisitSectionE.setTri24HrsShampoo(cursorE.getString(cursorE.getColumnIndex(Zpo04DBConstants.tri24HrsShampoo)));
        trimesterVisitSectionE.setTriBrandShampoo(cursorE.getString(cursorE.getColumnIndex(Zpo04DBConstants.triBrandShampoo)));
        trimesterVisitSectionE.setTriFragFreeShampoo(cursorE.getString(cursorE.getColumnIndex(Zpo04DBConstants.triFragFreeShampoo)));
        trimesterVisitSectionE.setTri24HrsOtherHair(cursorE.getString(cursorE.getColumnIndex(Zpo04DBConstants.tri24HrsOtherHair)));
        trimesterVisitSectionE.setTriBrandOtherHair(cursorE.getString(cursorE.getColumnIndex(Zpo04DBConstants.triBrandOtherHair)));
        trimesterVisitSectionE.setTriFragFreeOtherHair(cursorE.getString(cursorE.getColumnIndex(Zpo04DBConstants.triFragFreeOtherHair)));
        trimesterVisitSectionE.setTri24HrsPerfume(cursorE.getString(cursorE.getColumnIndex(Zpo04DBConstants.tri24HrsPerfume)));
        trimesterVisitSectionE.setTriBrandPerfume(cursorE.getString(cursorE.getColumnIndex(Zpo04DBConstants.triBrandPerfume)));
        trimesterVisitSectionE.setTriFragFreePerfume(cursorE.getString(cursorE.getColumnIndex(Zpo04DBConstants.triFragFreePerfume)));
        trimesterVisitSectionE.setTri24HrsBarSoap(cursorE.getString(cursorE.getColumnIndex(Zpo04DBConstants.tri24HrsBarSoap)));
        trimesterVisitSectionE.setTriBrandBarSoap(cursorE.getString(cursorE.getColumnIndex(Zpo04DBConstants.triBrandBarSoap)));
        trimesterVisitSectionE.setTriFragFreeBarSoap(cursorE.getString(cursorE.getColumnIndex(Zpo04DBConstants.triFragFreeBarSoap)));
        trimesterVisitSectionE.setTri24HrsLiqSoap(cursorE.getString(cursorE.getColumnIndex(Zpo04DBConstants.tri24HrsLiqSoap)));
        trimesterVisitSectionE.setTriBrandLiqSoap(cursorE.getString(cursorE.getColumnIndex(Zpo04DBConstants.triBrandLiqSoap)));
        trimesterVisitSectionE.setTriFragFreeLiqSoap(cursorE.getString(cursorE.getColumnIndex(Zpo04DBConstants.triFragFreeLiqSoap)));
        trimesterVisitSectionE.setTri24HrsLotion(cursorE.getString(cursorE.getColumnIndex(Zpo04DBConstants.tri24HrsLotion)));
        trimesterVisitSectionE.setTriBrandLotion(cursorE.getString(cursorE.getColumnIndex(Zpo04DBConstants.triBrandLotion)));
        trimesterVisitSectionE.setTriFragFreeLotion(cursorE.getString(cursorE.getColumnIndex(Zpo04DBConstants.triFragFreeLotion)));
        trimesterVisitSectionE.setTri24HrsShavCream(cursorE.getString(cursorE.getColumnIndex(Zpo04DBConstants.tri24HrsShavCream)));
        trimesterVisitSectionE.setTriBrandShavCream(cursorE.getString(cursorE.getColumnIndex(Zpo04DBConstants.triBrandShavCream)));
        trimesterVisitSectionE.setTriFragFreeShavCream(cursorE.getString(cursorE.getColumnIndex(Zpo04DBConstants.triFragFreeShavCream)));
        trimesterVisitSectionE.setTri24HrsColorCos(cursorE.getString(cursorE.getColumnIndex(Zpo04DBConstants.tri24HrsColorCos)));
        trimesterVisitSectionE.setTriBrandColorCos(cursorE.getString(cursorE.getColumnIndex(Zpo04DBConstants.triBrandColorCos)));
        trimesterVisitSectionE.setTriFragFreeColorCos(cursorE.getString(cursorE.getColumnIndex(Zpo04DBConstants.triFragFreeColorCos)));
        trimesterVisitSectionE.setTri24HrsSunscreen(cursorE.getString(cursorE.getColumnIndex(Zpo04DBConstants.tri24HrsSunscreen)));
        trimesterVisitSectionE.setTriBrandSunscreen(cursorE.getString(cursorE.getColumnIndex(Zpo04DBConstants.triBrandSunscreen)));
        trimesterVisitSectionE.setTriFragFreeSunscreen(cursorE.getString(cursorE.getColumnIndex(Zpo04DBConstants.triFragFreeSunscreen)));
        trimesterVisitSectionE.setTri24HrsNailPol(cursorE.getString(cursorE.getColumnIndex(Zpo04DBConstants.tri24HrsNailPol)));
        trimesterVisitSectionE.setTriBrandNailPol(cursorE.getString(cursorE.getColumnIndex(Zpo04DBConstants.triBrandNailPol)));
        trimesterVisitSectionE.setTriFragFreeNailPol(cursorE.getString(cursorE.getColumnIndex(Zpo04DBConstants.triFragFreeNailPol)));
        trimesterVisitSectionE.setTri24HrsFurnPol(cursorE.getString(cursorE.getColumnIndex(Zpo04DBConstants.tri24HrsFurnPol)));
        trimesterVisitSectionE.setTriBrandFurnPol(cursorE.getString(cursorE.getColumnIndex(Zpo04DBConstants.triBrandFurnPol)));
        trimesterVisitSectionE.setTriFragFreeFurnPol(cursorE.getString(cursorE.getColumnIndex(Zpo04DBConstants.triFragFreeFurnPol)));
        trimesterVisitSectionE.setTri24HrsCleaners(cursorE.getString(cursorE.getColumnIndex(Zpo04DBConstants.tri24HrsCleaners)));
        trimesterVisitSectionE.setTriBrandCleaners(cursorE.getString(cursorE.getColumnIndex(Zpo04DBConstants.triBrandCleaners)));
        trimesterVisitSectionE.setTriFragFreeCleaners(cursorE.getString(cursorE.getColumnIndex(Zpo04DBConstants.triFragFreeCleaners)));
        trimesterVisitSectionE.setTri24HrsFloorWax(cursorE.getString(cursorE.getColumnIndex(Zpo04DBConstants.tri24HrsFloorWax)));
        trimesterVisitSectionE.setTriBrandFloorWax(cursorE.getString(cursorE.getColumnIndex(Zpo04DBConstants.triBrandFloorWax)));
        trimesterVisitSectionE.setTriFragFreeFloorWax(cursorE.getString(cursorE.getColumnIndex(Zpo04DBConstants.triFragFreeFloorWax)));
        trimesterVisitSectionE.setTri24HrsSoftnr(cursorE.getString(cursorE.getColumnIndex(Zpo04DBConstants.tri24HrsSoftnr)));
        trimesterVisitSectionE.setTriBrandSoftnr(cursorE.getString(cursorE.getColumnIndex(Zpo04DBConstants.triBrandSoftnr)));
        trimesterVisitSectionE.setTriFragFreeSoftnr(cursorE.getString(cursorE.getColumnIndex(Zpo04DBConstants.triFragFreeSoftnr)));
        trimesterVisitSectionE.setTri24HrsLaundDet(cursorE.getString(cursorE.getColumnIndex(Zpo04DBConstants.tri24HrsLaundDet)));
        trimesterVisitSectionE.setTriBrandLaundDet(cursorE.getString(cursorE.getColumnIndex(Zpo04DBConstants.triBrandLaundDet)));
        trimesterVisitSectionE.setTriFragFreeLaundDet(cursorE.getString(cursorE.getColumnIndex(Zpo04DBConstants.triFragFreeLaundDet)));
        trimesterVisitSectionE.setTri24HrsLaundStrch(cursorE.getString(cursorE.getColumnIndex(Zpo04DBConstants.tri24HrsLaundStrch)));
        trimesterVisitSectionE.setTriBrandLaundStrch(cursorE.getString(cursorE.getColumnIndex(Zpo04DBConstants.triBrandLaundStrch)));
        trimesterVisitSectionE.setTriFragFreeLaundStrch(cursorE.getString(cursorE.getColumnIndex(Zpo04DBConstants.triFragFreeLaundStrch)));
        trimesterVisitSectionE.setTri24HrsPaint(cursorE.getString(cursorE.getColumnIndex(Zpo04DBConstants.tri24HrsPaint)));
        trimesterVisitSectionE.setTriBrandPaint(cursorE.getString(cursorE.getColumnIndex(Zpo04DBConstants.triBrandPaint)));
        trimesterVisitSectionE.setTriFragFreePaint(cursorE.getString(cursorE.getColumnIndex(Zpo04DBConstants.triFragFreePaint)));
        trimesterVisitSectionE.setTri24HrsSolvents(cursorE.getString(cursorE.getColumnIndex(Zpo04DBConstants.tri24HrsSolvents)));
        trimesterVisitSectionE.setTriBrandSolvents(cursorE.getString(cursorE.getColumnIndex(Zpo04DBConstants.triBrandSolvents)));
        trimesterVisitSectionE.setTriFragFreeSolvents(cursorE.getString(cursorE.getColumnIndex(Zpo04DBConstants.triFragFreeSolvents)));
        trimesterVisitSectionE.setTri24HrsCarWax(cursorE.getString(cursorE.getColumnIndex(Zpo04DBConstants.tri24HrsCarWax)));
        trimesterVisitSectionE.setTriBrandCarWax(cursorE.getString(cursorE.getColumnIndex(Zpo04DBConstants.triBrandCarWax)));
        trimesterVisitSectionE.setTriFragFreeCarWax(cursorE.getString(cursorE.getColumnIndex(Zpo04DBConstants.triFragFreeCarWax)));
        trimesterVisitSectionE.setTri24HrsPest(cursorE.getString(cursorE.getColumnIndex(Zpo04DBConstants.tri24HrsPest)));
        trimesterVisitSectionE.setTriBrandPest(cursorE.getString(cursorE.getColumnIndex(Zpo04DBConstants.triBrandPest)));
        trimesterVisitSectionE.setTriFragFreePest(cursorE.getString(cursorE.getColumnIndex(Zpo04DBConstants.triFragFreePest)));
        trimesterVisitSectionE.setTri24HrsFleaTickPrev(cursorE.getString(cursorE.getColumnIndex(Zpo04DBConstants.tri24HrsFleaTickPrev)));
        trimesterVisitSectionE.setTriBrandFleaTickPrev(cursorE.getString(cursorE.getColumnIndex(Zpo04DBConstants.triBrandFleaTickPrev)));
        trimesterVisitSectionE.setTriFleaTickPrev(cursorE.getString(cursorE.getColumnIndex(Zpo04DBConstants.triFleaTickPrev)));
        trimesterVisitSectionE.setTri24HrsFleaTickSpry(cursorE.getString(cursorE.getColumnIndex(Zpo04DBConstants.tri24HrsFleaTickSpry)));
        trimesterVisitSectionE.setTriBrandFleaTickSpry(cursorE.getString(cursorE.getColumnIndex(Zpo04DBConstants.triBrandFleaTickSpry)));
        trimesterVisitSectionE.setTriFleaTickSpry(cursorE.getString(cursorE.getColumnIndex(Zpo04DBConstants.triFleaTickSpry)));
        trimesterVisitSectionE.setTri24HrsCaritin(cursorE.getString(cursorE.getColumnIndex(Zpo04DBConstants.tri24HrsCaritin)));
        trimesterVisitSectionE.setTriBrandCaritin(cursorE.getString(cursorE.getColumnIndex(Zpo04DBConstants.triBrandCaritin)));
        trimesterVisitSectionE.setTriFragFreeCaritin(cursorE.getString(cursorE.getColumnIndex(Zpo04DBConstants.triFragFreeCaritin)));
        trimesterVisitSectionE.setTri24HrsZyrtec(cursorE.getString(cursorE.getColumnIndex(Zpo04DBConstants.tri24HrsZyrtec)));
        trimesterVisitSectionE.setTriBrandZyrtec(cursorE.getString(cursorE.getColumnIndex(Zpo04DBConstants.triBrandZyrtec)));
        trimesterVisitSectionE.setTriFragFreeZyrtec(cursorE.getString(cursorE.getColumnIndex(Zpo04DBConstants.triFragFreeZyrtec)));
        trimesterVisitSectionE.setTri24HrsVita(cursorE.getString(cursorE.getColumnIndex(Zpo04DBConstants.tri24HrsVita)));
        trimesterVisitSectionE.setTriBrandVita(cursorE.getString(cursorE.getColumnIndex(Zpo04DBConstants.triBrandVita)));
        trimesterVisitSectionE.setTriFragFreeVita(cursorE.getString(cursorE.getColumnIndex(Zpo04DBConstants.triFragFreeVita)));
        trimesterVisitSectionE.setTri24HrsHerbal(cursorE.getString(cursorE.getColumnIndex(Zpo04DBConstants.tri24HrsHerbal)));
        trimesterVisitSectionE.setTriBrandHerbal(cursorE.getString(cursorE.getColumnIndex(Zpo04DBConstants.triBrandHerbal)));
        trimesterVisitSectionE.setTriFragFreeHerbal(cursorE.getString(cursorE.getColumnIndex(Zpo04DBConstants.triFragFreeHerbal)));
        trimesterVisitSectionE.setTri24HrsCreatine(cursorE.getString(cursorE.getColumnIndex(Zpo04DBConstants.tri24HrsCreatine)));
        trimesterVisitSectionE.setTriBrandCreatine(cursorE.getString(cursorE.getColumnIndex(Zpo04DBConstants.triBrandCreatine)));
        trimesterVisitSectionE.setTriFragFreeCreatine(cursorE.getString(cursorE.getColumnIndex(Zpo04DBConstants.triFragFreeCreatine)));
        trimesterVisitSectionE.setTri24HrsProtein(cursorE.getString(cursorE.getColumnIndex(Zpo04DBConstants.tri24HrsProtein)));
        trimesterVisitSectionE.setTriBrandProtein(cursorE.getString(cursorE.getColumnIndex(Zpo04DBConstants.triBrandProtein)));
        trimesterVisitSectionE.setTriFragFreeProtein(cursorE.getString(cursorE.getColumnIndex(Zpo04DBConstants.triFragFreeProtein)));
        trimesterVisitSectionE.setTri24HrsDiuretic(cursorE.getString(cursorE.getColumnIndex(Zpo04DBConstants.tri24HrsDiuretic)));
        trimesterVisitSectionE.setTriBrandDiuretic(cursorE.getString(cursorE.getColumnIndex(Zpo04DBConstants.triBrandDiuretic)));
        trimesterVisitSectionE.setTriFragFreeDiuretic(cursorE.getString(cursorE.getColumnIndex(Zpo04DBConstants.triFragFreeDiuretic)));
        trimesterVisitSectionE.setTri24HrsInsulin(cursorE.getString(cursorE.getColumnIndex(Zpo04DBConstants.tri24HrsInsulin)));
        trimesterVisitSectionE.setTriBrandInsulin(cursorE.getString(cursorE.getColumnIndex(Zpo04DBConstants.triBrandInsulin)));
        trimesterVisitSectionE.setTriFragFreeInsulin(cursorE.getString(cursorE.getColumnIndex(Zpo04DBConstants.triFragFreeInsulin)));
        trimesterVisitSectionE.setTri24HrsMouthwsh(cursorE.getString(cursorE.getColumnIndex(Zpo04DBConstants.tri24HrsMouthwsh)));
        trimesterVisitSectionE.setTriBrandMouthwsh(cursorE.getString(cursorE.getColumnIndex(Zpo04DBConstants.triBrandMouthwsh)));
        trimesterVisitSectionE.setTriFragFreeMouthwsh(cursorE.getString(cursorE.getColumnIndex(Zpo04DBConstants.triFragFreeMouthwsh)));
        trimesterVisitSectionE.setTriFragFreeOverall(cursorE.getString(cursorE.getColumnIndex(Zpo04DBConstants.triFragFreeOverall)));
        trimesterVisitSectionE.setTriSurgInd(cursorE.getString(cursorE.getColumnIndex(Zpo04DBConstants.triSurgInd)));

        //Movil y Metadata
        if(cursorE.getLong(cursorE.getColumnIndex(MainDBConstants.recordDate))>0) trimesterVisitSectionE.setRecordDate(new Date(cursorE.getLong(cursorE.getColumnIndex(MainDBConstants.recordDate))));
        trimesterVisitSectionE.setRecordUser(cursorE.getString(cursorE.getColumnIndex(MainDBConstants.recordUser)));
        trimesterVisitSectionE.setPasive(cursorE.getString(cursorE.getColumnIndex(MainDBConstants.pasive)).charAt(0));
        trimesterVisitSectionE.setIdInstancia(cursorE.getInt(cursorE.getColumnIndex(MainDBConstants.ID_INSTANCIA)));
        trimesterVisitSectionE.setInstancePath(cursorE.getString(cursorE.getColumnIndex(MainDBConstants.FILE_PATH)));
        trimesterVisitSectionE.setEstado(cursorE.getString(cursorE.getColumnIndex(MainDBConstants.STATUS)));
        trimesterVisitSectionE.setStart(cursorE.getString(cursorE.getColumnIndex(MainDBConstants.START)));
        trimesterVisitSectionE.setEnd(cursorE.getString(cursorE.getColumnIndex(MainDBConstants.END)));
        trimesterVisitSectionE.setSimserial(cursorE.getString(cursorE.getColumnIndex(MainDBConstants.SIM_SERIAL)));
        trimesterVisitSectionE.setPhonenumber(cursorE.getString(cursorE.getColumnIndex(MainDBConstants.PHONE_NUMBER)));
        trimesterVisitSectionE.setDeviceid(cursorE.getString(cursorE.getColumnIndex(MainDBConstants.DEVICE_ID)));
        if(cursorE.getLong(cursorE.getColumnIndex(MainDBConstants.TODAY))>0) trimesterVisitSectionE.setToday(new Date(cursorE.getLong(cursorE.getColumnIndex(MainDBConstants.TODAY))));

        return trimesterVisitSectionE;
    }

    /*********************************************************
     PARA OBJETO Zpo04ExtendedSectionF
     *********************************************************/
    public static ContentValues crearZpo04ExtendedSectionF(Zpo04ExtendedSectionF trimesterVisitSectionFtoH){
        ContentValues cv = new ContentValues();

        cv.put(Zpo04DBConstants.recordId, trimesterVisitSectionFtoH.getRecordId());
        cv.put(Zpo04DBConstants.eventName, trimesterVisitSectionFtoH.getEventName());
        cv.put(Zpo04DBConstants.triBugNuisInd, trimesterVisitSectionFtoH.getTriBugNuisInd());
        cv.put(Zpo04DBConstants.triPestStorHomeInd, trimesterVisitSectionFtoH.getTriPestAppHomeInd());
        cv.put(Zpo04DBConstants.triPestAppHomeInd, trimesterVisitSectionFtoH.getTriPestAppHomeInd());
        cv.put(Zpo04DBConstants.triPestAppDay, trimesterVisitSectionFtoH.getTriPestAppDay());
        cv.put(Zpo04DBConstants.triPestAppMonth, trimesterVisitSectionFtoH.getTriPestAppMonth());
        cv.put(Zpo04DBConstants.triPestAppYear, trimesterVisitSectionFtoH.getTriPestAppYear());
        cv.put(Zpo04DBConstants.triPestAppName, trimesterVisitSectionFtoH.getTriPestAppName());
        cv.put(Zpo04DBConstants.triHomeTrtdInsctInd, trimesterVisitSectionFtoH.getTriHomeTrtdInsctInd());
        cv.put(Zpo04DBConstants.triHomeTrtdLoc, trimesterVisitSectionFtoH.getTriHomeTrtdLoc());
        cv.put(Zpo04DBConstants.triHomeTrtdEntity, trimesterVisitSectionFtoH.getTriHomeTrtdEntity());
        cv.put(Zpo04DBConstants.triHomeTrtdNames, trimesterVisitSectionFtoH.getTriHomeTrtdNames());
        cv.put(Zpo04DBConstants.triTrtmntAppDay, trimesterVisitSectionFtoH.getTriTrtmntAppDay());
        cv.put(Zpo04DBConstants.triTrtmntAppMonth, trimesterVisitSectionFtoH.getTriTrtmntAppMonth());
        cv.put(Zpo04DBConstants.triTrtmntAppYear, trimesterVisitSectionFtoH.getTriTrtmntAppYear());
        cv.put(Zpo04DBConstants.triLwnTrtmntAppInd, trimesterVisitSectionFtoH.getTriLwnTrtmntAppInd());
        cv.put(Zpo04DBConstants.triLwnTrtmntAppDay, trimesterVisitSectionFtoH.getTriLwnTrtmntAppDay());
        cv.put(Zpo04DBConstants.triLwnTrtmntAppMonth, trimesterVisitSectionFtoH.getTriLwnTrtmntAppMonth());
        cv.put(Zpo04DBConstants.triLwnTrtmntAppYear, trimesterVisitSectionFtoH.getTriLwnTrtmntAppYear());
        cv.put(Zpo04DBConstants.triLwnTrtmntAppName, trimesterVisitSectionFtoH.getTriPestAppName());
        cv.put(Zpo04DBConstants.triMosqRepInd, trimesterVisitSectionFtoH.getTriMosqRepInd());
        cv.put(Zpo04DBConstants.triMosqRepTyp, trimesterVisitSectionFtoH.getTriMosqRepTyp());
        cv.put(Zpo04DBConstants.triMosqRepNameSpray, trimesterVisitSectionFtoH.getTriMosqRepNameSpray());
        cv.put(Zpo04DBConstants.triMosqRepDkSpray, trimesterVisitSectionFtoH.getTriMosqRepDkSpray());
        cv.put(Zpo04DBConstants.triMosqRepNameLotion, trimesterVisitSectionFtoH.getTriMosqRepNameLotion());
        cv.put(Zpo04DBConstants.triMosqRepDkLotion, trimesterVisitSectionFtoH.getTriMosqRepDkLotion());
        cv.put(Zpo04DBConstants.triMosqRepNameSpiral, trimesterVisitSectionFtoH.getTriMosqRepNameSpiral());
        cv.put(Zpo04DBConstants.triMosqRepDkSpiral, trimesterVisitSectionFtoH.getTriMosqRepDkSpiral());
        cv.put(Zpo04DBConstants.triMosqRepNamePlugin, trimesterVisitSectionFtoH.getTriMosqRepNamePlugin());
        cv.put(Zpo04DBConstants.triMosqRepDkPlugin, trimesterVisitSectionFtoH.getTriMosqRepDkPlugin());
        cv.put(Zpo04DBConstants.triMosqRepNameOther, trimesterVisitSectionFtoH.getTriMosqRepNameOther());
        cv.put(Zpo04DBConstants.triMosqRepDkOther, trimesterVisitSectionFtoH.getTriMosqRepDkOther());
        cv.put(Zpo04DBConstants.triCompId, trimesterVisitSectionFtoH.getTriCompId());
        if (trimesterVisitSectionFtoH.getTriCompDat()!=null) cv.put(Zpo04DBConstants.triCompDat, trimesterVisitSectionFtoH.getTriCompDat().getTime());
        cv.put(Zpo04DBConstants.triRevId, trimesterVisitSectionFtoH.getTriRevId());
        if (trimesterVisitSectionFtoH.getTriRevDat()!=null) cv.put(Zpo04DBConstants.triRevDat, trimesterVisitSectionFtoH.getTriRevDat().getTime());
        cv.put(Zpo04DBConstants.triEntId, trimesterVisitSectionFtoH.getTriEntId());
        if (trimesterVisitSectionFtoH.getTriEntDat()!=null) cv.put(Zpo04DBConstants.triEntDat, trimesterVisitSectionFtoH.getTriEntDat().getTime());

        if (trimesterVisitSectionFtoH.getRecordDate() != null) cv.put(MainDBConstants.recordDate, trimesterVisitSectionFtoH.getRecordDate().getTime());
        cv.put(MainDBConstants.recordUser, trimesterVisitSectionFtoH.getRecordUser());
        cv.put(MainDBConstants.pasive, String.valueOf(trimesterVisitSectionFtoH.getPasive()));
        cv.put(MainDBConstants.ID_INSTANCIA, trimesterVisitSectionFtoH.getIdInstancia());
        cv.put(MainDBConstants.FILE_PATH, trimesterVisitSectionFtoH.getInstancePath());
        cv.put(MainDBConstants.STATUS, trimesterVisitSectionFtoH.getEstado());
        cv.put(MainDBConstants.START, trimesterVisitSectionFtoH.getStart());
        cv.put(MainDBConstants.END, trimesterVisitSectionFtoH.getEnd());
        cv.put(MainDBConstants.DEVICE_ID, trimesterVisitSectionFtoH.getDeviceid());
        cv.put(MainDBConstants.SIM_SERIAL, trimesterVisitSectionFtoH.getSimserial());
        cv.put(MainDBConstants.PHONE_NUMBER, trimesterVisitSectionFtoH.getPhonenumber());
        if (trimesterVisitSectionFtoH.getToday() != null) cv.put(MainDBConstants.TODAY, trimesterVisitSectionFtoH.getToday().getTime());

        return cv;
    }

    public static Zpo04ExtendedSectionF crearZpo04ExtendedSectionF(Cursor cursorFH){
        Zpo04ExtendedSectionF trimesterVisitSectionFtoH = new Zpo04ExtendedSectionF();

        trimesterVisitSectionFtoH.setRecordId(cursorFH.getString(cursorFH.getColumnIndex(Zpo04DBConstants.recordId)));
        trimesterVisitSectionFtoH.setEventName(cursorFH.getString(cursorFH.getColumnIndex(Zpo04DBConstants.eventName)));
        trimesterVisitSectionFtoH.setTriBugNuisInd(cursorFH.getString(cursorFH.getColumnIndex(Zpo04DBConstants.triBugNuisInd)));
        trimesterVisitSectionFtoH.setTriPestStorHomeInd(cursorFH.getString(cursorFH.getColumnIndex(Zpo04DBConstants.triPestStorHomeInd)));
        trimesterVisitSectionFtoH.setTriPestAppHomeInd(cursorFH.getString(cursorFH.getColumnIndex(Zpo04DBConstants.triPestAppHomeInd)));
        trimesterVisitSectionFtoH.setTriPestAppDay(cursorFH.getString(cursorFH.getColumnIndex(Zpo04DBConstants.triPestAppDay)));
        trimesterVisitSectionFtoH.setTriPestAppMonth(cursorFH.getString(cursorFH.getColumnIndex(Zpo04DBConstants.triPestAppMonth)));
        trimesterVisitSectionFtoH.setTriPestAppYear(cursorFH.getString(cursorFH.getColumnIndex(Zpo04DBConstants.triPestAppYear)));
        trimesterVisitSectionFtoH.setTriPestAppName(cursorFH.getString(cursorFH.getColumnIndex(Zpo04DBConstants.triPestAppName)));
        trimesterVisitSectionFtoH.setTriHomeTrtdInsctInd(cursorFH.getString(cursorFH.getColumnIndex(Zpo04DBConstants.triHomeTrtdInsctInd)));
        trimesterVisitSectionFtoH.setTriHomeTrtdLoc(cursorFH.getString(cursorFH.getColumnIndex(Zpo04DBConstants.triHomeTrtdLoc)));
        trimesterVisitSectionFtoH.setTriHomeTrtdEntity(cursorFH.getString(cursorFH.getColumnIndex(Zpo04DBConstants.triHomeTrtdEntity)));
        trimesterVisitSectionFtoH.setTriHomeTrtdNames(cursorFH.getString(cursorFH.getColumnIndex(Zpo04DBConstants.triHomeTrtdNames)));
        trimesterVisitSectionFtoH.setTriTrtmntAppDay(cursorFH.getString(cursorFH.getColumnIndex(Zpo04DBConstants.triTrtmntAppDay)));
        trimesterVisitSectionFtoH.setTriTrtmntAppMonth(cursorFH.getString(cursorFH.getColumnIndex(Zpo04DBConstants.triTrtmntAppMonth)));
        trimesterVisitSectionFtoH.setTriTrtmntAppYear(cursorFH.getString(cursorFH.getColumnIndex(Zpo04DBConstants.triTrtmntAppYear)));
        trimesterVisitSectionFtoH.setTriLwnTrtmntAppInd(cursorFH.getString(cursorFH.getColumnIndex(Zpo04DBConstants.triLwnTrtmntAppInd)));
        trimesterVisitSectionFtoH.setTriLwnTrtmntAppDay(cursorFH.getString(cursorFH.getColumnIndex(Zpo04DBConstants.triLwnTrtmntAppDay)));
        trimesterVisitSectionFtoH.setTriLwnTrtmntAppMonth(cursorFH.getString(cursorFH.getColumnIndex(Zpo04DBConstants.triLwnTrtmntAppMonth)));
        trimesterVisitSectionFtoH.setTriLwnTrtmntAppYear(cursorFH.getString(cursorFH.getColumnIndex(Zpo04DBConstants.triLwnTrtmntAppYear)));
        trimesterVisitSectionFtoH.setTriLwnTrtmntAppName(cursorFH.getString(cursorFH.getColumnIndex(Zpo04DBConstants.triLwnTrtmntAppName)));
        trimesterVisitSectionFtoH.setTriMosqRepInd(cursorFH.getString(cursorFH.getColumnIndex(Zpo04DBConstants.triMosqRepInd)));
        trimesterVisitSectionFtoH.setTriMosqRepTyp(cursorFH.getString(cursorFH.getColumnIndex(Zpo04DBConstants.triMosqRepTyp)));
        trimesterVisitSectionFtoH.setTriMosqRepNameSpray(cursorFH.getString(cursorFH.getColumnIndex(Zpo04DBConstants.triMosqRepNameSpray)));
        trimesterVisitSectionFtoH.setTriMosqRepDkSpray(cursorFH.getString(cursorFH.getColumnIndex(Zpo04DBConstants.triMosqRepDkSpray)));
        trimesterVisitSectionFtoH.setTriMosqRepNameLotion(cursorFH.getString(cursorFH.getColumnIndex(Zpo04DBConstants.triMosqRepNameLotion)));
        trimesterVisitSectionFtoH.setTriMosqRepDkLotion(cursorFH.getString(cursorFH.getColumnIndex(Zpo04DBConstants.triMosqRepDkLotion)));
        trimesterVisitSectionFtoH.setTriMosqRepNameSpiral(cursorFH.getString(cursorFH.getColumnIndex(Zpo04DBConstants.triMosqRepNameSpiral)));
        trimesterVisitSectionFtoH.setTriMosqRepDkSpiral(cursorFH.getString(cursorFH.getColumnIndex(Zpo04DBConstants.triMosqRepDkSpiral)));
        trimesterVisitSectionFtoH.setTriMosqRepNamePlugin(cursorFH.getString(cursorFH.getColumnIndex(Zpo04DBConstants.triMosqRepNamePlugin)));
        trimesterVisitSectionFtoH.setTriMosqRepDkPlugin(cursorFH.getString(cursorFH.getColumnIndex(Zpo04DBConstants.triMosqRepDkPlugin)));
        trimesterVisitSectionFtoH.setTriMosqRepNameOther(cursorFH.getString(cursorFH.getColumnIndex(Zpo04DBConstants.triMosqRepNameOther)));
        trimesterVisitSectionFtoH.setTriMosqRepDkOther(cursorFH.getString(cursorFH.getColumnIndex(Zpo04DBConstants.triMosqRepDkOther)));
        trimesterVisitSectionFtoH.setTriCompId(cursorFH.getString(cursorFH.getColumnIndex(Zpo04DBConstants.triCompId)));
        if (cursorFH.getLong(cursorFH.getColumnIndex(Zpo04DBConstants.triCompDat))>0) trimesterVisitSectionFtoH.setTriCompDat(new Date(cursorFH.getLong(cursorFH.getColumnIndex(Zpo04DBConstants.triCompDat))));
        trimesterVisitSectionFtoH.setTriRevId(cursorFH.getString(cursorFH.getColumnIndex(Zpo04DBConstants.triRevId)));
        if (cursorFH.getLong(cursorFH.getColumnIndex(Zpo04DBConstants.triRevDat))>0) trimesterVisitSectionFtoH.setTriRevDat(new Date(cursorFH.getLong(cursorFH.getColumnIndex(Zpo04DBConstants.triRevDat))));
        trimesterVisitSectionFtoH.setTriEntId(cursorFH.getString(cursorFH.getColumnIndex(Zpo04DBConstants.triEntId)));
        if (cursorFH.getLong(cursorFH.getColumnIndex(Zpo04DBConstants.triEntDat))>0) trimesterVisitSectionFtoH.setTriEntDat(new Date(cursorFH.getLong(cursorFH.getColumnIndex(Zpo04DBConstants.triEntDat))));

        //Movil y Metadata
        if(cursorFH.getLong(cursorFH.getColumnIndex(MainDBConstants.recordDate))>0) trimesterVisitSectionFtoH.setRecordDate(new Date(cursorFH.getLong(cursorFH.getColumnIndex(MainDBConstants.recordDate))));
        trimesterVisitSectionFtoH.setRecordUser(cursorFH.getString(cursorFH.getColumnIndex(MainDBConstants.recordUser)));
        trimesterVisitSectionFtoH.setPasive(cursorFH.getString(cursorFH.getColumnIndex(MainDBConstants.pasive)).charAt(0));
        trimesterVisitSectionFtoH.setIdInstancia(cursorFH.getInt(cursorFH.getColumnIndex(MainDBConstants.ID_INSTANCIA)));
        trimesterVisitSectionFtoH.setInstancePath(cursorFH.getString(cursorFH.getColumnIndex(MainDBConstants.FILE_PATH)));
        trimesterVisitSectionFtoH.setEstado(cursorFH.getString(cursorFH.getColumnIndex(MainDBConstants.STATUS)));
        trimesterVisitSectionFtoH.setStart(cursorFH.getString(cursorFH.getColumnIndex(MainDBConstants.START)));
        trimesterVisitSectionFtoH.setEnd(cursorFH.getString(cursorFH.getColumnIndex(MainDBConstants.END)));
        trimesterVisitSectionFtoH.setSimserial(cursorFH.getString(cursorFH.getColumnIndex(MainDBConstants.SIM_SERIAL)));
        trimesterVisitSectionFtoH.setPhonenumber(cursorFH.getString(cursorFH.getColumnIndex(MainDBConstants.PHONE_NUMBER)));
        trimesterVisitSectionFtoH.setDeviceid(cursorFH.getString(cursorFH.getColumnIndex(MainDBConstants.DEVICE_ID)));
        if(cursorFH.getLong(cursorFH.getColumnIndex(MainDBConstants.TODAY))>0) trimesterVisitSectionFtoH.setToday(new Date(cursorFH.getLong(cursorFH.getColumnIndex(MainDBConstants.TODAY))));

        return trimesterVisitSectionFtoH;
    }

}
